### ISSUE TITLE
DEV: CLI Deployments E2E Failing with 

### ISSUE THREAD

**Issue by nkapinos** [astronomer/astro-cli#1019]
**Describe the bug**

CLI Deployments e2e is failing consistently after retries.   This is in DEV and is using compiled SNAPSHOT version.

```
Error:       CypressError: `cy.exec('astro deployment worker-queue create         -n e2e-wq-ofsse         -d clcv0who2202361iyudtu3ygt2         -t m5.xlarge')` failed because the command exited with a non-zero code.

Pass `{failOnNonZeroExit: false}` to ignore exit code failures.

Information about the failure:
Code: 1

Stderr:
Error: Error processing GraphQL request: API error (400): {"errors":[{"message":"Variable \"$input\" got invalid value \"2\" at \"input.workerQueues[0].podCpu\"; Float cannot represent non numeric ...
```

**What CLI Version did you experience this bug?**

**This CLI bug is related to which Astronomer Platform?**

- [x ] Astro
- [ ] Software
- [ ] None/Unknown

**What Operating System is the above CLI installed on?**
Linux / CircleCI runner

**🪜 Steps To Reproduce**

1.  Navigate to e2e job: https://app.circleci.com/pipelines/github/astronomer/astro/42744/workflows/3d3c422a-6ebf-42d8-9a5b-6e57ee50ff28/jobs/1290414

**📸 Screenshots**

**Comment by nkapinos** [comment]
![Screen Shot 2023-01-13 at 1.42.15 PM.png](https://images.zenhubusercontent.com/6138e91c9500e1afcacd653c/01ebf1bf-6645-4850-bfd3-c576006cfc39)

**Comment by jemishp** [comment]
The [fix](https://github.com/astronomer/astro-cli/pull/1017/commits/6891fa5be5ce55569a50e0c013d8dde949ccfdec) is in [PR](https://github.com/astronomer/astro-cli/pull/1017)
