### ISSUE TITLE
godownlaoder not working

### ISSUE THREAD

**Issue by jcom000** [astronomer/astro-cli#1044]
**Describe the bug**

godownlaoder not working

```
curl -sSL install.astronomer.io | sudo bash -s
astronomer/astro-cli info checking GitHub for latest tag
astronomer/astro-cli info found version:  <!DOCTYPE html> <html lang= for  <!DOCTYPE html> <html lang=/linux/amd64

Exited with code exit status 1
```

**Comment by jemishp** [comment]
The issue is in `godownlaoder.sh` specifically in `github_release()`

```
  test -z "$version" && version="latest"
  giturl="https://github.com/${owner_repo}/releases/${version}"
  json=$(http_copy "$giturl" "Accept:application/json")
```

For some reason we are not getting back json array of artifacts and instead getting the actual html page for `1.9.0` release.

**Comment by jemishp** [comment]
Symptom is a github issue: https://github.com/orgs/community/discussions/45590

**Comment by neel-astro** [comment]
This has been addressed from the GitHub end as well been improved from our end in #1045
