### ISSUE TITLE
astro login logs me with a different user

### ISSUE THREAD

**Issue by kushalmalani** [astronomer/astro-cli#1079]
astro login picks up existing session which leads to a user A being logged in the browser and you are trying to login with user B.

Slack Thread - https://astronomer.slack.com/archives/C03HRT0MRPD/p1676347969216169

**Comment by nkapinos** [comment]
Causing failure of e2e: https://app.circleci.com/pipelines/github/astronomer/astro/49744/workflows/d484a076-2d7b-4198-bdb4-ee6aa039ed96/jobs/1732314/steps
