### ISSUE TITLE
CLI: `astro deploy` status

### ISSUE THREAD

**Issue by sunkickr** [astronomer/astro-cli#1086]
- [X] I have checked that a similar [feature request](https://github.com/astronomer/astro-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**✍️ Is your feature request related to a problem? Please describe.**

Today when you run `astro deploy` you don't know if your code was applied correctly. If docker push was successful you get a success message but issues after he push could cause your deploy to not work or for your deployment to become unsuccessful.

**🧩 Describe the solution you'd like**

The astro deploy command should always give you the status of your deployment after a deploy wether that is healthy, unhealthy, unknown, or creating. If the status is deploying the CLI should continually poll until it receives a healthy or unhealthy status. Unknown should be displayed but only if it is continuously received. The point of polling and showing status is so that users know that their changes were successfully applied after a deploy. If possible user should be told why their deployment become unhealthy.

Examples:

Successful deploy - `astro deploy --wait`:

```
Successfully pushed Docker image to Astronomer registry.

Deployment my-deployment is currently deploying... This may take a few minutes.

Your Deploy has finished Successfully.
NAME                 my-deployment
DEPLOYMENT ID        cl8bx6swa178701iz1tesba3u9
DEPLOYMENT STATUS    HEALTHY
DOCKER IMAGE TAG     deploy-2022-08-11T14-22 # this is ideally the tag currently being run in the webserver 
RUNTIME VERSION      6.0.0 (based on Airflow 2.4.0)

Deployment can be accessed at the following URLs: 

 Deployment Dashboard: cloud.astronomer-dev.io/ckmzjm22937931d35puw3tcdo/deployments/cl8bx6swa178701iz1tesba3u9
 Airflow Dashboard: astronomer.astronomer-dev.run/desba3u9?orgId=org_dlgevirUCwI9vX10
 ```
 
 Unsuccessfully deploy - `astro deploy --wait` - webserver crashes after deploy
 
 ```
 Successfully pushed Docker image to Astronomer registry.

Deployment my-deployment is currently deploying... This may take a few minutes.

ERROR: The Deploy was unsucessful. The Deployment my-deployment is unhealthy:
Your Deployment’s webserver is not reponding

Deployment Information
NAME                 my-deployment
DEPLOYMENT ID        cl8bx6swa178701iz1tesba3u9
DEPLOYMENT STATUS    UNHEALTHY
DOCKER IMAGE TAG     deploy-2022-08-11T14-22 # this is ideally the tag currently being run in the webserver 
RUNTIME VERSION      6.0.0 (based on Airflow 2.4.0)

Check it out at the Deployment URLs below, debug, and try deploying again with 'astro deploy --wait': 

 Deployment Dashboard: cloud.astronomer-dev.io/ckmzjm22937931d35puw3tcdo/deployments/cl8bx6swa178701iz1tesba3u9
 Airflow Dashboard: astronomer.astronomer-dev.run/desba3u9?orgId=org_dlgevirUCwI9vX10
 ```
 
 Unsuccessfully deploy - `astro deploy --wait` - docker push failed(status should show even code doesn't get deployed):
 
 ```
ERROR: Permssioned Denied:

There was an error while pushing your docker image. Your deployment will not update

Deployment Information
NAME                 my-deployment
DEPLOYMENT ID        cl8bx6swa178701iz1tesba3u9
DEPLOYMENT STATUS    HEALTHY
DOCKER IMAGE TAG     deploy-2022-08-11T14-22 # this is ideally the tag currently being run in the webserver 
RUNTIME VERSION      6.0.0 (based on Airflow 2.4.0)

Check it out at the Deployment URLs below, debug, and try deploying again with 'astro deploy --wait': 

 Deployment Dashboard: cloud.astronomer-dev.io/ckmzjm22937931d35puw3tcdo/deployments/cl8bx6swa178701iz1tesba3u9
 Airflow Dashboard: astronomer.astronomer-dev.run/desba3u9?orgId=org_dlgevirUCwI9vX10
 ```

**🤔 Describe alternatives you've considered**

**Is your feature request specific to a particular Astronomer Platform?**

- [X] Astro
- [ ] Software
- [ ] None/Unknown

**💡 Additional context**

#4 in solution alignment in this document: https://www.notion.so/astronomerio/CLI-Deploy-Feedback-ec283f96a86348a9b61941e00f469603

**Comment by sunkickr** [comment]
The deployment should only wait for healthy status if the users uses the --wait flag(like in create). Make sure changes don't cause users to loose information

**Comment by adammarples** [comment]
I would add that I've been working around this by polling the `astro deployment inspect --key metadata.status` and have been running into issues because it takes the api about 25 seconds to even realise it is `DEPLOYING` after the deploy command runs, so it reports that it is `HEALTHY` when I poll. 

Therefore I'm in the odd situation of first having to poll for it to begin being in `DEPLOYING` status, then check for `HEALTHY`. This is critical for actually having reliable deployments in CICD that can be automatically tested.


```bash
status-check () {
  # Keep polling until deployment reaches desired status
  until {
    local health=$(astro deployment inspect --clean-output --workspace-id $ASTRO_WORKSPACE_ID --deployment-name $ASTRO_DEPLOYMENT_NAME -k metadata.status)
    echo "status: $health, waiting for $1"
    test "$health" = "$1"
  }
  do
    echo "Retrying in $2 seconds..."
    sleep $2
  done
}

status-check "DEPLOYING" 1
status-check "HEALTHY" 10
```

**Comment by adammarples** [comment]
Thank you very much @kushalmalani
