### ISSUE TITLE
CLI: Flag to force platform type for local dev

### ISSUE THREAD

**Issue by cmarteepants** [astronomer/astro-cli#1100]
For runtime images, we support using an M1 platform for local dev for performance reasons. If the user is running on ARM, we build an ARM-compatible image for local dev purposes, and build an AMD image when deploying to Astro. However, there are some cases where users need to install tools like DB drivers that are platform specific. This poses an issue where they need one version of drivers for local dev, and another version of drivers for deploying to Astro. 

We need the ability for users to specify a platform via our CLI for local dev purposes, and pass that arg down to docker. For example `astro dev start --platform amd64`

Here's a slack conversation where the user talks about the issue: https://apache-airflow.slack.com/archives/C03T0AVNA6A/p1677683693355239

**Comment by jedcunningham** [comment]
As a workaround, or alternative solution, users can also set a `DOCKER_DEFAULT_PLATFORM=linux/amd64` env var or specify the platform in their Dockerfile like so:

`FROM --platform=linux/amd64 quay.io/astronomer/astro-runtime:7.3.0`

**Comment by wei-astronomer** [comment]
@cmarteepants with Jed's suggestion, do we still need this flag in CLI? Or we can check if that's an acceptable option.

cc @jemishp @sunkickr

**Comment by sunkickr** [comment]
setting your Dockerfile to FROM --platform=linux/amd64 [quay.io/astronomer/astro-runtime:7.3.0](http://quay.io/astronomer/astro-runtime:7.3.0) works just fine
