### ISSUE TITLE
Expose `webserver.host`

### ISSUE THREAD

**Issue by tversteeg** [astronomer/astro-cli#1103]
- [x] I have checked that a similar [feature request](https://github.com/astronomer/astro-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist, though it is related to #1082.

**✍️ Is your feature request related to a problem? Please describe.**

I would to allow setting the hostname to which the local dev HTTP server is bound, for example to `0.0.0.0`, so I can connect to it from different machines without having to mess around with proxies.

**🧩 Describe the solution you'd like**

Add a  `webserver.host` config option for the Astro CLI.

**🤔 Describe alternatives you've considered**

A local proxy, but this is a pain to set up.

Another possible workaround I found is creating a `docker-compose.override.yml` with the following setup:

```yaml
version: "3.4"

services:
  webserver:
    ports:
     - 0.0.0.0:8081:8080
```

Unfortunately, binding to `0.0.0.0:8080` doesn't work here and this is only a project specific configuration.

**Is your feature request specific to a particular Astronomer Platform?**

- [x] Astro
- [ ] Software
- [ ] None/Unknown

**Comment by neel-astro** [comment]
from astro cli version 1.12.0 onwards, one can set `airflow.expose_port` in CLI config to true to expose the webserver & postgres port over `0.0.0.0` which should help resolve your issue.

command to set the config: `astro config set -g airflow.expose_port true`

**Comment by ChuliangXiao** [comment]
> from astro cli version 1.12.0 onwards, one can set `airflow.expose_port` in CLI config to true to expose the webserver & postgres port over `0.0.0.0` which should help resolve your issue.
> 
> command to set the config: `astro config set -g airflow.expose_port true`

Worked for me.
