### ISSUE TITLE
astro deployment create --wait doesn't recognize created deployment

### ISSUE THREAD

**Issue by BasPH** [astronomer/astro-cli#1128]
`astro deployment create --wait` doesn't complete when the deployment has been created (according to the UI), and eventually shows a conflicting error message after timing out:

```
Current Workspace: Professional Services

Waiting for the deployment to become healthy…

This may take a few minutes
Error: timed out waiting for the deployment to become healthy
 NAME                              NAMESPACE                     CLUSTER                  DEPLOYMENT ID                   RUNTIME VERSION                    DAG DEPLOY ENABLED     
 branch-new-branch-for-testing     elementary-cosmology-2196     AstroDataEngineering     clfk5ra4x1162518hvzed9di3z6     7.4.1 (based on Airflow 2.5.2)     false                  

 Successfully created Deployment: branch-new-branch-for-testing
 Deployment can be accessed at the following URLs 

 Deployment Dashboard: cloud.astronomer.io/clbkx9he4229155kdz2tl8bv7vq/deployments/clfk5ra4x1162518hvzed9di3z6/analytics
 Airflow Dashboard: astronomer.astronomer.run/dd9di3z6
```

I would expect the command to complete around the same time that the UI shows the deployment is created successfully. More context in https://astronomer.slack.com/archives/CL44PA4DB/p1679518828834409.

**What CLI Version did you experience this bug?**

Tested on 1.10 and all versions above

**This CLI bug is related to which Astronomer Platform?**

- [ ] Astro
- [ ] Software
- [ ] None/Unknown

**What Operating System is the above CLI installed on?**

**🪜 Steps To Reproduce**

**📸 Screenshots**

**Comment by sunkickr** [comment]
This is covered in issue here: https://github.com/astronomer/astro-cli/issues/1085
