### ISSUE TITLE
Pip dependency resolution with requirements.txt

### ISSUE THREAD

**Issue by abhishekbhakat** [astronomer/astro-cli#1139]
- [x] I have checked that a similar [feature request](https://github.com/astronomer/astro-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**✍️ Is your feature request related to a problem? Please describe.**

As pip installing `requirements.txt` happens on top of the current state of libs, it uninstalls and overwrites preinstalled packages in the docker image. A simple option like `astro dev pipresolve` help users decide on a specific packages and any conflicts it can cause.

**🧩 Describe the solution you'd like**

Like to replicate the following steps:

```
FROM quay.io/astronomer/astro-runtime:7.4.2
USER root
RUN pip install pip-tools
RUN pip freeze > req.txt
RUN cat requirements.txt >> req.txt
RUN sed -i '/\.whl/d' req.txt
RUN python -m piptools compile --verbose req.txt -o result.txt
```

**🤔 Describe alternatives you've considered**

I use the above `Dockerfile` with a simple `docker run` command to get the result.txt on the host machine.

**Is your feature request specific to a particular Astronomer Platform?**

- [ ] Astro
- [ ] Software
- [x] No

**💡 Additional context**

**Comment by RNHTTR** [comment]
This allows users to understand any potential dependency conflicts prior to building an Astro image. It could be particularly useful to give confidence prior to upgrading Airflow. This works with the following Dockerfile (along with `gnupg` added to packages.txt):

```
FROM quay.io/astronomer/astro-runtime:7.5.0
USER root
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list
RUN apt -y update
RUN ACCEPT_EULA=Y apt-get install -y msodbcsql18
RUN apt-get install -y unixodbc-dev
RUN pip install pip-tools
RUN pip freeze > req.txt
RUN cat requirements.txt >> req.txt
RUN sed -i '/\.whl/d' req.txt
# RUN cat req.txt | grep -v '.whl' > req.txt
RUN python -m piptools compile --verbose req.txt -o result.txt
```

Unclear if the mssql stuff is necessary.

**Comment by kaxil** [comment]
@sunkickr is working on this one

**Comment by sunkickr** [comment]
new github issue https://github.com/astronomer/astro-cli/issues/1306
