### ISSUE TITLE
astro workspace update with -n (workspace name) doesn't select workspace

### ISSUE THREAD

**Issue by BasPH** [astronomer/astro-cli#1159]
**Describe the bug**

astro workspace update with -n (workspace name) doesn't select the workspace as expected (I obfuscated the workspace names but the name "test-nonprod" exists and is unique).

```
astro workspace update -n test-nonprod -e ON -d "This is a test workspace"

Please select the workspace you would like to update:
#      WORKSPACENAME     ID                CICD ENFORCEMENT
1      [obfuscated]      [obfuscated]      true
2      [obfuscated]      [obfuscated]      true
3      [obfuscated]      [obfuscated]      true
4      [obfuscated]      [obfuscated]      true
5      [obfuscated]      [obfuscated]      true
6      [obfuscated]      [obfuscated]      true
7      [obfuscated]      [obfuscated]      true

>
```

**What CLI Version did you experience this bug?**

1.14.0

**This CLI bug is related to which Astronomer Platform?**

- [ ] Astro
- [ ] Software
- [ ] None/Unknown

**What Operating System is the above CLI installed on?**

**🪜 Steps To Reproduce**

**📸 Screenshots**

**Comment by kushalmalani** [comment]
You need to pass the workspace id, otherwise you would be asked to select the workspace to which you are looking to update

`astro workspace update [workspace_id] [flags]`

-n flag is for you to update the name

**Comment by kushalmalani** [comment]
@BasPH Going to close this ticket since i dont think this is a bug. Feel free to re-open and add your comments.
