### ISSUE TITLE
OAuth token persists for multiple users in terminal session 

### ISSUE THREAD

**Issue by bonominijl** [astronomer/astro-cli#116]
**Users:**
User1 (Created the workspace and deployment in Cloud2)
User2 (Some nobody trying to get some free cloud resources)

**Steps to reproduce:**
1. As user1, create a new account on Cloud2 (app.astronomer.io)
2. As user1, authenticate into your workspace through the CLI
3. Create a new deployment through the CLI and deploy an example DAG into the deployment
4. In the same terminal session, authenticate against cloud2 as user2
5. Run `astro deployment list` and verify that user2 can see the deployment created by user1
6. Deploy the same example dag as user2, into the deployment created by user1

**Expected outcome:**
User2 cannot see or deploy to deployments created by user1

**Actual outcome:**
The token created by user1 is accessible to user2, allowing them to deploy into an instance they are not a part of. 

![2018-08-23-1535039735_screenshot_1920x1080](https://user-images.githubusercontent.com/7431155/44538272-d7469100-a6ce-11e8-80ed-1216d68d94b1.jpg)

**Comment by andscoop** [comment]
The permissions issue will be resolved with https://github.com/astronomerio/houston-api/pull/49

I am going to leave this ticket open as there is more than can be done on the CLI to provide a better user experience around this.

For a cluster we should store the auth'd user and the preferred workspace for each auth'd user. This will involve a slight config rework

**Comment by andriisoldatenko** [comment]
@ryw can we close it or retest and close?

**Comment by schnie** [comment]
@andriisoldatenko would you mind giving this a test? The original PR was never merged, but I believe this would be taken care of with Houston 2. If you can't recreate, lets close it out.
