### ISSUE TITLE
DEV-Standard clusters: Unable to create deployment through CLI

### ISSUE THREAD

**Issue by shri-astro** [astronomer/astro-cli#1188]
An attempt to create a Standard hosted deployment displayed the below error.
Same error is seen from the UI as well

```
shrividyahegde@10 test_dep % ./astro deployment create -n test111 -p gcp --dag-deploy enable -e CeleryExecutor -v 8.0.0 -a enable --region us-central1 --scheduler-size small --clean-output
Current Workspace: SH

Error: Error occurred while creating deployment: Organization is inactive. Please contact Astronomer support.
```

**What CLI Version did you experience this bug?**
SNAPSHOT-266b5f36

**This CLI bug is related to which Astronomer Platform?**

- [ ] Astro Hosted 

**What Operating System is the above CLI installed on?**
Ventura 13.3.1 (a) (22E772610a)

**Comment by kushalmalani** [comment]
This should be resolved now.

**Comment by shri-astro** [comment]
I just saw this issue with the same binary.Not sure if I'm missing something here:
shrividyahegde@10 test_dep % ./astro version                                                                                                                                                
Astro CLI Version: SNAPSHOT-266b5f36
shrividyahegde@10 test_dep % ./astro deployment create -n test111 -p gcp --dag-deploy enable -e CeleryExecutor -v 8.0.0 -a enable --region us-central1 --scheduler-size small --clean-output

Error: unknown shorthand flag: 'p' in -p
Usage:
  astro deployment create [flags]

Aliases:
  create, cr

Flags:
      --clean-output             clean output to only include inspect yaml or json file in any situation.
  -c, --cluster-id string        Cluster to create the Deployment in
      --dag-deploy string        Enables DAG-only deploys for the deployment (default "disable")
      --deployment-file string   Location of file containing the deployment to create. File can be in either JSON or YAML format.
  -d, --description string       Description of the Deployment. If the description contains a space, specify the entire description in quotes ""
  -e, --executor string          The executor to use for the deployment. Possible values can be CeleryExecutor or KubernetesExecutor.
  -h, --help                     help for create
  -n, --name string              The Deployment's name. If the name contains a space, specify the entire name within quotes "" 
  -v, --runtime-version string   Runtime version for the Deployment
  -s, --scheduler-au int         The Deployment's Scheduler resources in AUs
  -r, --scheduler-replicas int   The number of Scheduler replicas for the Deployment
  -i, --wait                     Wait for the Deployment to become healthy before ending the command
  -w, --workspace-id string      Workspace to create the Deployment in

Global Flags:
      --verbosity string   Log level (debug, info, warn, error, fatal, panic (default "warning")

**Comment by shri-astro** [comment]
fixed
