### ISSUE TITLE
Can we link the upgrade notification to the release notes?

### ISSUE THREAD

**Issue by stuart23** [astronomer/astro-cli#1197]
I often receive the [Consider upgrading to the latest version](https://github.com/astronomer/astro-cli/blob/0e4b0e2381387d0ed2d26ace77197dbae927d2db/cloud/deploy/deploy.go#LL710C3-L710C3) warning, but chose to ignore it as there is no clear benefit of upgrading. Should we link it to the release notes so people know what they are missing out on?

**Comment by kushalmalani** [comment]
I merged the PR with this fix. Fix will be released next week as part of 1.27.0
