### ISSUE TITLE
DEV- User is able to create duplicate deployments through CLI

### ISSUE THREAD

**Issue by shri-astro** [astronomer/astro-cli#1198]
Deployment creation through UI doesn't allow deployments with same names (duplicate deployment )creation.
However through CLI, executing the following command two times creates 2 deployments which are identical.

```
 ./astro deployment create -n test111 -p gcp --dag-deploy enable -e CeleryExecutor -v 8.1.0 -a enable --region us-central1 --scheduler-size small --clean-output
```

**What CLI Version did you experience this bug?**

Astro CLI Version: SNAPSHOT-266b5f36

**This CLI bug is related to which Astronomer Platform?**

- [ ] Astro

**Comment by kushalmalani** [comment]
Not sure if this is a bug. You can create multiple deployments with the same name from the UI as well

![Screenshot 2023-05-14 at 20 10 22](https://github.com/astronomer/astro-cli/assets/65428224/498b7b0e-1b78-4432-86f3-e95e1faf9840)

**Comment by shri-astro** [comment]
While this issue was raised, we were getting the error message as "Deployment with the same name exists" in the UI.However now I'm able to create duplicate deployments through the UI.
@ryanahamilton  could you please confirm if this is expected change?

**Comment by ryanahamilton** [comment]
I'm unaware of any restriction on unique Deployment naming. I would expect that we allow it given the `id` and `namespace` will surely remain unique.

**Comment by shri-astro** [comment]
sure. Marking this as resolved.
Thanks @ryanahamilton and @kushalmalani
