### ISSUE TITLE
DEV- For a trial account deployment, the second deployment create won't show in the CLI

### ISSUE THREAD

**Issue by shri-astro** [astronomer/astro-cli#1203]
For the trial account with a total of 2 deployments supported, both the deployments were created with Celery and Kubernetes executor type and the CLI command to list the deployment was executed. 
```
astro deployment list
```
Out of the two deployments only one showed up in CLI while both the deployments are seen in the UI.

Effect:
Not able to upload dags to another deployment

Details:
-Deployments tried with Celery and Kubernetes - Kubernetes deployment didn't show up
-To check if the executor type is the root cause , both the deployments with the Kubernetes executor were created  and still only one of them showed up.
-API tokens were used to login for this

Output text:
```
shrividyahegde@Shrividyas-MacBook-Pro test_dep % ./astro deployment list
Using an Astro API key
 NAME     NAMESPACE                       CLUSTER     DEPLOYMENT ID                 RUNTIME VERSION                    DAG DEPLOY ENABLED     
 Test     uninhabited-atmosphere-1913     N/A         clhk8y55m27931jyfdo1qi44s     8.1.0 (based on Airflow 2.6.0)     true                   
shrividyahegde@Shrividyas-MacBook-Pro test_dep % 

```

**This CLI bug is related to which Astronomer Platform?**

- [ ] Astro

**📸 Screenshots**

<img width="1728" alt="Screenshot 2023-05-12 at 4 15 00 PM" src="https://github.com/astronomer/astro-cli/assets/101165534/aeb35e67-422c-4d41-b019-d32ce702f372">

**Comment by kushalmalani** [comment]
Unable to replicate this

![Screenshot 2023-05-14 at 19 41 18](https://github.com/astronomer/astro-cli/assets/65428224/faf62247-0173-42ba-885a-e69b3a822ad9)
![Screenshot 2023-05-14 at 19 41 40](https://github.com/astronomer/astro-cli/assets/65428224/95641df0-4aec-4eba-8e9b-66d813d6b7ea)

**Comment by shri-astro** [comment]
@kushalmalani were u also able to deploy dags to the second deployment?

**Comment by kushalmalani** [comment]
@shri-astro Yes, i was using those deployments for testing auth0 creds issue. Can you try again and confirm if its still an issue you are facing

**Comment by shri-astro** [comment]
The issue seems to be resolved:
```
shrividyahegde@Shrividyas-MacBook-Pro test_dep % astro deployment list                                                                                                                                      
 NAME             NAMESPACE     CLUSTER         DEPLOYMENT ID                  RUNTIME VERSION                    DAG DEPLOY ENABLED     
 test_cli         N/A           us-central1     clht43t7z704821iwcyjas8iqx     8.2.0 (based on Airflow 2.6.1)     true                   
 aws_standard     N/A           us-central1     clht3x32a669731iwy91rvtxx5     8.2.0 (based on Airflow 2.6.1)     false 
 ```
