### ISSUE TITLE
Consolidate Astro CLI guides / docs / readme

### ISSUE THREAD

**Issue by tedmiston** [astronomer/astro-cli#122]
There are CLI guides / docs spread across a number of files today.  As a CLI user, it's not immediately obvious which one is the most current or if one is authoritative.

- https://github.com/astronomerio/astro-cli/blob/master/README.md
- https://github.com/astronomerio/airflow-guides/blob/master/guides/astro-cli.md
- https://github.com/astronomerio/airflow-guides/blob/master/guides_in_progress/astro-cli.md
- https://github.com/astronomerio/airflow-guides/blob/master/guides/cli.md
- https://github.com/astronomerio/airflow-guides/blob/master/guides_in_progress/apache_airflow/cli.md
- https://github.com/astronomerio/airflow-guides/blob/master/guides_in_progress/deploying-dags-with-astro-cli.md

These docs also have some CLI stuff

- https://github.com/astronomerio/airflow-guides/blob/master/guides_in_progress/migrating-dags.md
- https://github.com/astronomerio/airflow-guides/blob/master/guides/getting-started-with-new-cloud.md
- https://github.com/astronomerio/airflow-guides/blob/f2742bc82d7668a9ca796b773978345990ec9860/guides_in_progress/creating-an-airflow-project.md
- https://github.com/astronomerio/airflow-guides/blob/master/guides_in_progress/creating-an-airflow-project.md

What do we think of consolidating all of these into one place?

/cc @andscoop

**Comment by ryw** [comment]
@benjamingregory want to take a look at this?

**Comment by benjamingregory** [comment]
New docs structure has consolidated CLI docs: 

https://github.com/astronomer/docs/blob/master/docs/cli-getting-started.md
https://github.com/astronomer/docs/blob/master/docs/cli-installation.md
https://github.com/astronomer/docs/blob/master/docs/cli-installation-windows-10.md
https://github.com/astronomer/docs/blob/master/docs/cli-command-reference.md
https://github.com/astronomer/docs/blob/0.8/docs/cli-airflow-configuration.md
