### ISSUE TITLE
Customer upgraded to runtime 6.4 using old CLI, upgraded to the new CLI and now can't deploy

### ISSUE THREAD

**Issue by alex-astronomer** [astronomer/astro-cli#1223]
**Describe the bug**

![image](https://github.com/astronomer/astro-cli/assets/89415310/ddef02ab-3b9f-445d-96e1-d6cdaa513f3e)

**What CLI Version did you experience this bug?**

v1.15

**This CLI bug is related to which Astronomer Platform?**

- [ ] Astro
- [x] Software
- [ ] None/Unknown

**What Operating System is the above CLI installed on?**

**🪜 Steps To Reproduce**

Upgrade from AC to Runtime using old version of CLI (Software specific, pre-convergence)

**First Thoughts**

Error message comes from https://github.com/astronomer/astro-cli/blob/5d18a2277410376ce8fe7bda465ca044f5be3587/software/deployment/deployment.go#L385

I believe that the old version of the CLI was not populating the RuntimeVersion for the deployment, because it wasn't designed to deal with runtime.  Need to restore customer's functionality ASAP.

**ZD Ticket**

https://astronomer.zendesk.com/agent/tickets/19765

Customer: Everlywell

**Comment by neel-astro** [comment]
This was resolved on Slack, just a confusion between airflow & runtime upgrade command in CLI for software
Reference: https://astronomer.slack.com/archives/C03HRT0MRPD/p1684786998587699
