### ISSUE TITLE
Enhancement for workspace related commands

### ISSUE THREAD

**Issue by shri-astro** [astronomer/astro-cli#1244]
Whenever there is a single deployment in a given workspace any dag deployment when attempted, takes the deployment by default and doesn't ask the user to choose the deployment(as there is only 1 deployment).
The same thing is currently not applicable for workspace related commands.
In the following command the update operation is tried on workspace and the user is asked to select the workspace even when there is just one workspace.

```
shrividyahegde@Shrividyas-MacBook-Pro test_dep % ./astro workspace update -e "ON"      

Please select the workspace you would like to update:
 #     WORKSPACENAME     ID                            CICD ENFORCEMENT     
 1     third             clik76vt4002e01rpl94eg6da     false                

> 1
Astro Workspace third was successfully updated
```

**What CLI Version did you experience this bug?**
Astro CLI Version: SNAPSHOT-b2c8f859 (pre-release)

**This CLI bug is related to which Astronomer Platform?**

- [ ] Astro
**What Operating System is the above CLI installed on?**
Apple M1 Pro

**Comment by kushalmalani** [comment]
This should be in latest main

**Comment by shri-astro** [comment]
shrividyahegde@Shrividyas-MacBook-Pro ~ % astro workspace update -e "ON"
Only one Workspace was found. Using the following Workspace by default: 

 Workspace Name: Test Automated Workspace
 Workspace ID: clix0m97m001i01oiqr98vqb5

Astro Workspace Test Automated Workspace was successfully updated
