### ISSUE TITLE
Usage fields on `workspace token` commands  reference nonexistent `TOKEN_ID`

### ISSUE THREAD

**Issue by jwitz** [astronomer/astro-cli#1258]
**Describe the bug**

The usage field on `astro workspace token` commands says you can specify a `TOKEN_ID`, but this doesn't exist in the product from what I can tell. You can only choose a token or give a name, but trying to add the token itself as an ID doesn't work. Therefore I assume that this is a mistake and might lead users to spend time searching for a nonexistent ID.

```
astro workspace token update [TOKEN_ID] [flags]
```

**What CLI Version did you experience this bug?**

16.1

**This CLI bug is related to which Astronomer Platform?**

- [X] Astro
- [ ] Software
- [ ] None/Unknown

**What Operating System is the above CLI installed on?**

MacOS

**Comment by sunkickr** [comment]
TOKEN_ID is the only unique identifier which is needed for automation. The TOKEN_ID will need to be added to the UI
