### ISSUE TITLE
astro dev not using .dockerignore

### ISSUE THREAD

**Issue by adammarples** [astronomer/astro-cli#1262]
**Describe the bug**

`astro dev start` builds a container that seems to ignore the .dockerignore file 

**What CLI Version did you experience this bug?**

Astro CLI Version: 1.16.1

**This CLI bug is related to which Astronomer Platform?**

- [x] Astro
- [ ] Software
- [ ] None/Unknown

**What Operating System is the above CLI installed on?**

MacOS 13.4 Ventura
astro from homebrew

**🪜 Steps To Reproduce**

1. start a clean dir and initialise example project 
```
mkdir astro-docker
cd astro-docker
astro dev init
ls -hal

Permissions Size User        Date Modified Name
drwxr-xr-x     - adammarples 15 Jun 10:08  .astro
.rw-r--r--    44 adammarples 15 Jun 10:08  .dockerignore
.rw-r--r--     0 adammarples 15 Jun 10:08  .env
.rw-r--r--    85 adammarples 15 Jun 10:08  .gitignore
.rw-r--r--   852 adammarples 15 Jun 10:08  airflow_settings.yaml
drwxr-xr-x     - adammarples 15 Jun 10:08  dags
.rw-r--r--    44 adammarples 15 Jun 10:08  Dockerfile
drwxr-xr-x     - adammarples 15 Jun 10:08  include
.rw-r--r--     0 adammarples 15 Jun 10:08  packages.txt
drwxr-xr-x     - adammarples 15 Jun 10:08  plugins
.rw-r--r--  3.2k adammarples 15 Jun 10:08  README.md
.rw-r--r--   151 adammarples 15 Jun 10:08  requirements.txt
drwxr-xr-x     - adammarples 15 Jun 10:08  tests
```

2. Check .dockerignore is ignoring my creds

```
cat .dockerignore

astro
.git
.env
 airflow_settings.yaml
logs/
```

3. start the dev docker container

```
astro dev start
```

4. look inside

```
astro dev bash

Execing into the scheduler container

astro@d15a9edb4218:/usr/local/airflow$ ls -hal
total 112K
drwxrwxr-x 1 astro root  4.0K Jun 15 09:09 .
drwxr-xr-x 1 root  root  4.0K Jun  2 16:03 ..
drwxr-xr-x 2 astro root  4.0K Jun 15 09:09 .astro
-rw-r--r-- 1 astro root    44 Jun 15 09:08 .dockerignore
-rw-r--r-- 1 astro root    85 Jun 15 09:08 .gitignore
-rw-r--r-- 1 astro root    44 Jun 15 09:08 Dockerfile
-rw-r--r-- 1 astro root  3.2K Jun 15 09:08 README.md
-rw------- 1 astro astro  57K Jun 15 09:09 airflow.cfg
-rw-r--r-- 1 root  root   852 Jun 15 09:08 airflow_settings.yaml
drwxr-xr-x 6 root  root   192 Jun 15 09:09 dags
drwxr-xr-x 2 root  root    64 Jun 15 09:08 include
drwxrwxr-x 4 astro root  4.0K Jun 15 09:09 logs
-rw-r--r-- 1 astro root     0 Jun 15 09:08 packages.txt
drwxr-xr-x 2 root  root    64 Jun 15 09:08 plugins
-rw-r--r-- 1 astro root   252 Jun 15 09:09 requirements.txt
drwxr-xr-x 3 root  root    96 Jun 15 09:08 tests
-rw-r--r-- 1 astro astro 4.7K Jun 15 09:09 webserver_config.py

```

There are my creds `airflow_settings.yaml` which are supposed to be ignored. `.env` is not there though

**Comment by neel-astro** [comment]
Tried it locally with the latest Astro CLI version, and the `.dockerignore` logic seems to be working fine.
`airflow_settings.yaml` is supposed to hold airflow connections, pools & variables for the local project only, and hence if the file is present it is added to the local airflow container so that the local project can maintain airflow connections, pools & variables easily via `astro dev object import` & `astro dev object export` commands.

**Comment by neel-astro** [comment]
Closing this, feel free to reopen if you have any other question
