### ISSUE TITLE
[bug] Team User List errors out when 0 members

### ISSUE THREAD

**Issue by chomipi88** [astronomer/astro-cli#1269]
**Describe the bug**

`astro organization team user list` errors out when the team has 0 members. Works fine after adding a user.

![image](https://github.com/astronomer/astro-cli/assets/87984472/abaf951e-3e8b-4108-a5c0-ec1ca65db0de)
![image](https://github.com/astronomer/astro-cli/assets/87984472/a5a520b5-ae65-4b0e-a19b-78f90f1346c7)

**Comment by kushalmalani** [comment]
@aliotta Seems like this is fixed. Closing this
