### ISSUE TITLE
Shift the CI/CD Enforcement Check Left

### ISSUE THREAD

**Issue by ReadytoRocc** [astronomer/astro-cli#1282]
Currently, `astro deploy` will pull, build, test, and push my image to Astro, before checking if CI/CD enforcement has been enabled on the target Runtime deployment.

Is it possible to initially check if CI/CD enforcement has been enabled to fail fast and inform the user that this action is not allowed? 

This will save users' time and resources.

**Comment by kushalmalani** [comment]
Duplicate of (https://github.com/astronomer/astro-cli/issues/1276)
