### ISSUE TITLE
Add timeout on github client

### ISSUE THREAD

**Issue by neel-astro** [astronomer/astro-cli#1291]
**Describe the bug**

As of now GitHub client does not have timeouts in any form, as a result whenever there is an issue on the GitHub end, Astro CLI ends up in a hang state, because CLI makes a GitHub API call in almost all command execution to figure out if a user is using the latest CLI version or not. This is not a blocker call from the functionality of any CLI command, so we can have an aggressive timeout as well.

```
Please paste terminal or playground output in a code block here
```

**What CLI Version did you experience this bug?**

**This CLI bug is related to which Astronomer Platform?**

- [x] Astro
- [x] Software
- [ ] None/Unknown

**What Operating System is the above CLI installed on?**

**🪜 Steps To Reproduce**

**📸 Screenshots**

**Comment by kushalmalani** [comment]
@neel-astro Can we close this?
