### ISSUE TITLE
v1.17.0 broke in CI

### ISSUE THREAD

**Issue by adammarples** [astronomer/astro-cli#1297]
**Describe the bug**

Overnight the CI build broke because v1.17.0 could not be pulled

```bash
astronomer/astro-cli info checking GitHub for tag 'v1.17.0'
astronomer/astro-cli crit unable to find 'v1.17.0' - use 'latest' or see https://github.com/astronomer/astro-cli/releases for details
##[error]Bash exited with code '1'.
```

v1.17.0

**This CLI bug is related to which Astronomer Platform?**

- [x] Astro
- [ ] Software
- [ ] None/Unknown

**What Operating System is the above CLI installed on?**

ubuntu-latest

**🪜 Steps To Reproduce**

curl -sSL install.astronomer.io | sudo bash -s -- v1.17.0

What is weird is that I have been using v1.17.0 all week, since upgrading from v1.16.1, but when I look at your releases page, v1.17.0 has been out only 18 hours.

**Comment by adammarples** [comment]
This now works again. The only difference I could see was that while it was failing, v1.17.0 had a 'pre-release' sticker.

**Comment by neel-astro** [comment]
1.17.0 is still in the pre-release stage, which means devs could be ironing out any potential bugs, and the release can get recreated when new changes are pushed. In your case, your CI might have tried to install the 1.17.0 release when it was being recreated.
Ideally, if you are consuming Astro CLI for any use case, then you should avoid pre-releases and stick to the release marked as the latest. That could be done using the `curl -sSL install.astronomer.io | sudo bash -s` command which will ensure that the latest available stable release is installed.

**Comment by adammarples** [comment]
Thanks @neel-astro

**Comment by neel-astro** [comment]
I am closing this issue since 1.17.0 is released now, and it should be ok to use it in production use cases. @adammarples feel free to reopen if you have any other concerns.
