### ISSUE TITLE
Expose Workload identity in deployment inspect

### ISSUE THREAD

**Issue by stuart23** [astronomer/astro-cli#1324]
- [x] I have checked that a similar [feature request](https://github.com/astronomer/astro-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**✍️ Is your feature request related to a problem? Please describe.**

Can we please expose the role ARN in the deployments inspect output? https://astronomer.zendesk.com/agent/tickets/24819

**🧩 Describe the solution you'd like**

`astro deployment inspect -n cre-airline-dev --key metadata.workload_identity`

**🤔 Describe alternatives you've considered**

**Is your feature request specific to a particular Astronomer Platform?**

- [x] Astro
- [ ] Software
- [ ] None/Unknown

**💡 Additional context**

**Comment by kushalmalani** [comment]
Seems like this is addressed. Based on current output and confirmation on the Zendesk ticket
