### ISSUE TITLE
godownloader.sh has `sh` shebang but uses `bash`-specific `[[` keyword.

### ISSUE THREAD

**Issue by doxel-alex** [astronomer/astro-cli#1326]
**Describe the bug**

`godownloader.sh` has `sh` shebang but uses the `bash`-specific `[[` keyword. Users who download and execute `godownloader.sh` from file will end up using the Bourne shell due to the shebang, which will fail on lines 303 and 305. This may lead to undesired behavior.

```
$ ./astronomer.sh -b ~/bin/ v1.17.1
astronomer/astro-cli info checking GitHub for tag 'v1.17.1'
./astronomer.sh: 303: [[: not found
./astronomer.sh: 305: [[: not found
astronomer/astro-cli info found version: 1.17.1 for v1.17.1/linux/amd64
astronomer/astro-cli info installed /home/username/bin//astro

```

**What CLI Version did you experience this bug?**
This is an issue with the [`godownloader.sh`](https://github.com/astronomer/astro-cli/blob/main/godownloader.sh#L303) script, which is on `main` (currently [`b041b32`](https://github.com/astronomer/astro-cli/commit/b041b32ad094d31f09ab7fbbb12fa37bca48f804)).

**This CLI bug is related to which Astronomer Platform?**

- [ ] Astro
- [ ] Software
- [x] None/Unknown

**What Operating System is the above CLI installed on?**
Linux

**🪜 Steps To Reproduce**

1. Download `godownloader.sh`
2. `chmod u+x godownloader.sh`
3. `./godownloader.sh -b ~/bin/ v1.17.1`

**📸 Screenshots**
N/A

**Comment by kushalmalani** [comment]
@doxel-alex We addressed something for a different issue in this PR - https://github.com/astronomer/astro-cli/pull/1369/files

Can you confirm if this resolves the issue you are seeing.

**Comment by doxel-alex** [comment]
This addresses the issue I reported. Thank you!
