### ISSUE TITLE
New release on a new branch causes entire commit history to be uploaded to changelog

### ISSUE THREAD

**Issue by andscoop** [astronomer/astro-cli#133]
Currently if a new release is cut on a `release-x` branch, the entire commit history is uploaded. This is probably an issue with the goreleaser script that we easily can fix.

**Comment by andscoop** [comment]
Created a ticket with go-releaser to see if we will be able to resolved this without custom work on goreleaser.

**Comment by ryw** [comment]
@andscoop can you link that issue here?

**Comment by andscoop** [comment]
https://github.com/goreleaser/goreleaser/issues/817

**Comment by ryw** [comment]
@schnie is this still an issue?

**Comment by schnie** [comment]
Yes it is for us. We may need to update `goreleaser` or something though. Any idea @andriisoldatenko?

**Comment by andriisoldatenko** [comment]
@ryw @schnie yes it's exists. Let me jump on it in next release and fix it.

**Comment by andriisoldatenko** [comment]
@ryw @schnie done.
![image](https://user-images.githubusercontent.com/1374633/64454222-1afe1400-d0f3-11e9-82a6-24a02c6460e0.png)

**Comment by schnie** [comment]
Thanks @andriisoldatenko!
