### ISSUE TITLE
DEV- Unable to create deployments with same name

### ISSUE THREAD

**Issue by shri-astro** [astronomer/astro-cli#1346]
The deployments with same name are allowed to be created in the UI and used to be the case in CLI as well , although in 1.18.1 , I just observed that the dedicated deployment creation is throwing error as there is a standard deployment by the same name.

I'm able to create deployment with duplicate names when the name for the deployment is passed as a parameter to astro deployment create command with -n as a flag.

Slack conversation reference:
https://astronomer.slack.com/archives/C03HRT0MRPD/p1691485832179699

```
shrividyahegde@Shrividyas-MacBook-Pro ~ % astro deployment create --cluster-type "dedicated" -i
Current Workspace: Astro_hosted_CLI_Automation_Restricted_Workspace

Please specify a name for your Deployment

Deployment name: t
Error: A Deployment with that name already exists
```

**What CLI Version did you experience this bug?**

1.18.1

**This CLI bug is related to which Astronomer Platform?**

- [ ] Astro

**What Operating System is the above CLI installed on?**
Mac M1 Pro

**Comment by erdos2n** [comment]
@shri-astro can we verify if this is related to https://github.com/astronomer/astro-cli/issues/1360 ? 

Because the example in https://github.com/astronomer/astro-cli/issues/1360 uses a deployment file, I'm not sure if it's the same issue. 

Thanks

**Comment by shri-astro** [comment]
> @shri-astro can we verify if this is related to #1360 ?
> 
> Because the example in #1360 uses a deployment file, I'm not sure if it's the same issue.
> 
> Thanks

Sorry for the delayed response.This issue seems to be different, I'm able to create one if I pass the name but otherwise there is an error

**Comment by shri-astro** [comment]
Resolved for both standard and dedicated deployments
