### ISSUE TITLE
deployment create --deployment-file yaml cluster wide deployment ids are flagged as duplicated

### ISSUE THREAD

**Issue by erdos2n** [astronomer/astro-cli#1360]
**Describe the bug**
The following deployments can be created via the Astro UI, but the CLI will return the error
```bash
Error: deployment: deploymentA already exists: use deployment update --deployment-file my_deployment_file.yaml instead
Usage:
```

```mermaid
---
title: Duplicated Deployment Name Architecture
---
flowchart LR
    subgraph clusterA
         subgraph workspaceA
            dep1((deploymentA))
        end
         subgraph workspaceB
            dep2((deploymentA))
        end
   end
```

```bash
astro deployment create --deployment-file "my_deployment_file.yaml"
```

**What CLI Version did you experience this bug?**
v1.17.1

**This CLI bug is related to which Astronomer Platform?**

- [ X] Astro (Hosted Dedicated)
- [ ] Software
- [ ] None/Unknown

**What Operating System is the above CLI installed on?**
Mac M1 Max OS 13.5

**🪜 Steps To Reproduce**
1. Go to Astro Hosted
2. Created deployment `deploymentA` in workspaceA
3. Using astro cli run `astro deployment inspect -t <deploymentA id>` and save output to `deploymentA_duplicate.yaml`
4. Modify the `workspace_name` in `deploymentA_duplicate.yaml` from `workspaceA` to `workspaceB`.
5. Set `name: "deploymentA"` in `deploymentA_duplicate.yaml`
6. Run `astro deployment create --deployment-file "deploymentA_duplicate.yaml"`
7. See error

**Other Information**
* This has been replicated on `HOSTED_STANDARD` and `HOSTED_DEDICATED`
* Error was not seen on `HOSTED_SHARED`

**Comment by kushalmalani** [comment]
This has been fixed and will be released as part of 1.27.0 next week
