### ISSUE TITLE
Upgrade Test no longer producing html report

### ISSUE THREAD

**Issue by sunkickr** [astronomer/astro-cli#1382]
**Describe the bug**

`astro dev upgrade-test` command no longer produces an html report of the dag test

**What CLI Version did you experience this bug?**

v1.19.0 & v1.19.1

**This CLI bug is related to which Astronomer Platform?**

- [X] Astro
- [ ] Software
- [ ] None/Unknown

**What Operating System is the above CLI installed on?**

mac os

**🪜 Steps To Reproduce**

**📸 Screenshots**

**Comment by neel-astro** [comment]
Fixed as part of the `1.19.2` patch release
