### ISSUE TITLE
gcc is missing from the Python 3.11 image starting from astro-runtime 9.0.0

### ISSUE THREAD

**Issue by tangi-vass** [astronomer/astro-cli#1384]
On both astro-runtime 9.0.0 and 9.1.0, the image for python 3.11 is missing gcc so the installation of libs in requirements.txt requiring gcc (dependency-injector in my case) fails.

`astro deploy` with python 3.11:
```
23.62       creating build/temp.linux-x86_64-cpython-311/src/dependency_injector
23.62       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -I/usr/local/include/python3.11 -c src/dependency_injector/containers.c -o build/temp.linux-x86_64-cpython-311/src/dependency_injector/containers.o -O2
23.62       error: command 'gcc' failed: No such file or directory
23.62       [end of output]
23.62   
23.62   note: This error originates from a subprocess, and is likely not a problem with pip.
23.62   ERROR: Failed building wheel for dependency-injector
23.62   Running setup.py clean for dependency-injector
24.45 Failed to build dependency-injector
24.45 ERROR: Could not build wheels for dependency-injector, which is required to install pyproject.toml-based projects
------
Dockerfile:1
--------------------
   1 | >>> FROM quay.io/astronomer/astro-runtime:9.1.0-python-3.11
   2 |     
--------------------
```

With python 3.10:
```
FROM quay.io/astronomer/astro-runtime:9.1.0-python-3.10`
```
works fine.

**Comment by jedcunningham** [comment]
Runtime has never come with gcc in the final image (intentionally). I'm surprised it's trying to build from source instead of using a wheel.

If you use `--progress plain`, I'm sure you'll see 3.10 is using a wheel. e.g:

```
#9 2.200 Collecting dependency-injector (from -r requirements.txt (line 1))
#9 2.257   Downloading dependency_injector-4.41.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.0 MB)
```

When I try with 3.11, it also uses a wheel.

```
#9 1.990 Collecting dependency-injector (from -r requirements.txt (line 1))
#9 2.051   Downloading dependency_injector-4.41.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.4 MB)
```

Are you pulling in a specific version of dependency-injector?

**Comment by tangi-vass** [comment]
Thanks for the insights!

> Are you pulling in a specific version of dependency-injector?

Yes, `dependency-injector==4.39.1` as subsequent versions don't work with MacOS for local dev (https://github.com/ets-labs/python-dependency-injector/issues/553)

**Comment by tangi-vass** [comment]
When I was using Python 3.7, I had to pin several libs, including `dependency-injector` mentioned here. By upgrading to Python 3.11 and unpinning everything, it works fine. Thank you for the support.
