### ISSUE TITLE
astro dev pytest generated artifacts not persistant

### ISSUE THREAD

**Issue by SebOpo** [astronomer/astro-cli#1387]
**Describe the bug**

Acorrindg to docs https://docs.astronomer.io/astro/cli/astro-dev-pytest  all files saved in `include` folder should be accessible outside contianer. In v1.19.0 this feature was dissabled: https://github.com/astronomer/astro-cli/commit/046705c8b098aab1ac1ca7a01af7e874643ed61a
Without volume mounts all generated files i.e code coverage or test reports are gone along with the pytest container .

```
astro dev pytest --args "--cov --cov-report xml:include/coverage.xml"
```

**What CLI Version did you experience this bug?**

1.19.0+

**This CLI bug is related to which Astronomer Platform?**

- [x] Astro
- [x] Software
- [ ] None/Unknown

**What Operating System is the above CLI installed on?**

**🪜 Steps To Reproduce**

Run
``` 
astro dev pytest --args "--cov --cov-report xml:include/coverage.xml"
```
Check if "coverage.xml" file exists in `include` folder outside docker container after test has finished.

**Comment by sunkickr** [comment]
We removed the volumes because they were causing tests and dags to be missing in certain CI/CD tools we will have to think of a way to fix this issue with this in mind

**Comment by sunkickr** [comment]
@neel-astro idea is to simulate the old behavior by coping the include folder from the docker container to the local include folder after the pytest runs

**Comment by zach-nicoll-wcq** [comment]
Would love to see this fixed.

In fact, would love to fix it and open a PR.

I've found [this line](https://github.com/astronomer/astro-cli/blob/18d0c7515e5a614beb6860edb3d3179e6c4ecf79/airflow/docker_image.go#L169) that implies the test report is being copied out of the container using `docker cp`.

However, it doesn't look like `htmlReport` is being set to true at any point, so this isn't running.

Additionally, this doesn't take into account `.xml` coverage outputs.

Could we change the command to copy all `*.html` and `*.xml` files every time, regardless of `htmlReport` flag state?

Not sure who to @ here, so @sunkickr @neel-astro thoughts?
