### ISSUE TITLE
Add flags to skip tests in integrity testing

### ISSUE THREAD

**Issue by erdos2n** [astronomer/astro-cli#1398]
- [x] I have checked that a similar [feature request](https://github.com/astronomer/astro-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**✍️ Is your feature request related to a problem? Please describe.**
Users cannot bypass a particular test when running `astro dev pytest`. This has caused issues, because users have had to add the `-f` flag to their deploy command which will not alert them of any failed test. 

**🧩 Describe the solution you'd like**
Ideally, adding a config parameter that can be passed and parsed to skip a test, but a quicker solution is adding an env variable to the Dockerfile. 

Ex:

```python
@pytest.mark.skipif(
    os.getenv("SKIP_TEST_DAG_RETRIES").lower()=="true",
    reason="skipping dag retries test"
)
@pytest.mark.parametrize(
    "dag_id,dag, fileloc", get_dags(), ids=[x[2] for x in get_dags()]
)
def test_dag_retries(dag_id, dag, fileloc):
    """
    test if a DAG has retries set
    """
    assert (
        dag.default_args.get("retries", None) >= 2
    ), f"{dag_id} in {fileloc} does not have retries not set to 2."
```

**🤔 Describe alternatives you've considered**
Adding CLI variable that gets parsed

**Is your feature request specific to a particular Astronomer Platform?**

- [ ] Astro
- [ ] Software
- [X] None/Unknown

**💡 Additional context**
User wanted to have some level of integrity testing, but ignore the `test_dag_tags` test.

**Comment by collinmcnulty** [comment]
This seems like a reasonable step. We have had some cases where DAGs failed dag integrity test in their CI but worked on production. This was caused by top level Variable calls that didn't work on CI, which isn't best practice but was otherwise working.

**Comment by sunkickr** [comment]
Changed name of test to example test so that it is clear that users do not need to run the test.
