### ISSUE TITLE
Add support for .env file for secrets

### ISSUE THREAD

**Issue by vparekh94** [astronomer/astro-cli#140]
As a user, I might use private github repos to store python packages in my org. It would be nice to have the ability to pass those secrets in through some sort of .env file and be able to use them to auth+pip install from my git repo. 

@schnie I think this is a good summary of our conversation - anything to add?

**Comment by schnie** [comment]
Yep, looks good. We should probably add support for runtime env vars, as well as build time env vars.

**Comment by mplovepop** [comment]
I also would like this!

**Comment by benjamingregory** [comment]
We're working to get this included in the next CLI release but here is a workaround for now:
In you astronomer project (after `astro airflow init`)...
1) Put the following in a file labeled Dockerfile.build
```
FROM astronomerinc/ap-airflow:0.6.2 AS stage1
LABEL maintainer="Astronomer <humans@astronomer.io>"
ARG BUILD_NUMBER=-1
LABEL io.astronomer.docker=true
LABEL io.astronomer.docker.build.number=$BUILD_NUMBER
LABEL io.astronomer.docker.airflow.onbuild=true
# Install alpine packages
COPY packages.txt .
RUN cat packages.txt | xargs apk add --no-cache

FROM stage1 AS stage2
RUN mkdir -p /root/.ssh
ARG PRIVATE_RSA_KEY=""
RUN echo "${PRIVATE_RSA_KEY}" >> /root/.ssh/id_rsa
RUN chmod 600 /root/.ssh/id_rsa
RUN apk update && apk add openssh
RUN ssh-keyscan -H github.com >> /root/.ssh/known_hosts
# Install python packages
COPY requirements.txt .
RUN pip install --no-cache-dir -q -r requirements.txt

FROM stage1 AS stage3
# Copy requirements directory
COPY --from=stage2 /usr/lib/python3.6/site-packages/ /usr/lib/python3.6/site-packages/
```
2) Build the image with `docker build -f Dockerfile.build --build-arg PRIVATE_RSA_KEY="$(cat ~/.ssh/id_rsa)" -t custom-ap-airflow .` If your private key is not held at `~/.ssh/id_rsa`, change the reference to the relevant path.
3) Replace the contents of Dockerfile from `FROM astronomerinc/ap-airflow:latest-onbuild` to `FROM custom-ap-airflow`
4) Issue `astro airflow start`

**Comment by paolaperaza** [comment]
Thanks, @benjamingregory ! Posted this on our forum too, for reference.

https://forum.astronomer.io/t/how-do-i-install-something-from-my-orgs-private-github-repo-without-exposing-credentials/45/2

**Comment by benjamingregory** [comment]
Support for CLI is complete but we need to some thinking around distribution of the images. Right now, it looks like we'll need to change https://github.com/astronomer/astronomer/blob/master/docker/airflow/1.9.0/onbuild/Dockerfile to a multi-stage build with up to three separate images.

Stage1
```
FROM astronomerinc/ap-airflow:0.6.2 AS stage1
LABEL maintainer="Astronomer <humans@astronomer.io>"
ARG BUILD_NUMBER=-1
LABEL io.astronomer.docker=true
LABEL io.astronomer.docker.build.number=$BUILD_NUMBER
LABEL io.astronomer.docker.airflow.onbuild=true
# Install alpine packages
COPY packages.txt .
RUN cat packages.txt | xargs apk add --no-cache
```

Stage2
```
FROM astronomerinc/stage1 AS stage2
ONBUILD RUN mkdir -p /root/.ssh
ONBUILD ARG PRIVATE_RSA_KEY=""
ONBUILD RUN echo "${PRIVATE_RSA_KEY}" >> /root/.ssh/id_rsa
ONBUILD RUN chmod 600 /root/.ssh/id_rsa
ONBUILD RUN apk update && apk add openssh
ONBUILD RUN ssh-keyscan -H github.com >> /root/.ssh/known_hosts
# Install python packages
ONBUILD COPY requirements.txt .
ONBUILD RUN cat /root/.ssh/id_rsa
ONBUILD RUN pip install --no-cache-dir -q -r requirements.txt
```

Stage3
```
FROM astronomerinc/stage1 AS stage3
# Copy requirements directory
ONBUILD COPY --from=stage2 /usr/lib/python3.6/site-packages/ /usr/lib/python3.6/site-packages/
```

In this scenario, the Dockerfile created by the CLI would then consist of 
```
FROM astronomerinc/stage2
FROM astronominc/stage3
```

Because we're not sure if maintaining multiple images is the best way to proceed, @schnie has advised we pause on this issue to research this further.

Removing myself from assignment until we decide on how to proceed.

**Comment by benjamingregory** [comment]
Closing with our suggested solution of https://forum.astronomer.io/t/how-do-i-install-something-from-my-orgs-private-github-repo-without-exposing-credentials/45/2

No plans right now to do the multi-stage builds that this feature would require.
