### ISSUE TITLE
Always `--pull` when building image

### ISSUE THREAD

**Issue by jedcunningham** [astronomer/astro-cli#1407]
- [x] I have checked that a similar [feature request](https://github.com/astronomer/astro-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**✍️ Is your feature request related to a problem? Please describe.**

We'd like to start offering floating tags for Runtime (e.g. a `astro-runtime:9`) which will always point to the latest release in a given major. One challenge, however, is to make sure the latest image is used when building the image. 

**🧩 Describe the solution you'd like**

Add `--pull` to the build command.

**🤔 Describe alternatives you've considered**

We could alternatively document customers need to do an explicit pull before an `astro deploy` etc, but that seems easy to forget and not very polished. One extra request to make sure the image is up to date is pretty cheap (locally, typically .1 second or so).

**Is your feature request specific to a particular Astronomer Platform?**

- [ ] Astro
- [ ] Software
- [x] None/Unknown

**Comment by cmarteepants** [comment]
@vishwas-astro @nicholasfilippi - I see this is in icebox. Is this something we can prioritize please? This is a blocker for us publishing runtime images with floating tags for major runtime versions. 

If someone uses this batch of images, patch and minor runtime updates will happen automatically. If we don't change the pull method when building, docker will not check whether or not we have published a more recent version and will default to whatever is in the cache - meaning no automatic update.

**Comment by sunkickr** [comment]
does this fix the issue? https://github.com/astronomer/astro-cli/pull/1415

**Comment by jedcunningham** [comment]
Yes it does.
