### ISSUE TITLE
DeployConfig isn't returning correct runtime versions to create deployment Missing params

### ISSUE THREAD

**Issue by bote795** [astronomer/astro-cli#1417]
**Describe the bug**
When a user is trying to create a deployment for a deployment version that is in that users org they should be able to create it but through the CLI they are not able to since the values that are being returned from deploymentConfig doesn't include the ones that are available for that org since we are not passing the organizationId in the request.

https://github.com/astronomer/astro-cli/blob/2841f469370688c4063d4fd9bbb7560b8c9a235e/astro-client/astro.go#L116-L126
add `  "organizationId": "",`
to Variables sent in request

```
Please paste terminal or playground output in a code block here
```

**What CLI Version did you experience this bug?**

**This CLI bug is related to which Astronomer Platform?**

- [x] Astro
- [ ] Software
- [ ] None/Unknown

**What Operating System is the above CLI installed on?**

**🪜 Steps To Reproduce**

1. Have an organization with an deprecated deployment
2. try to create a deployment with that deprecated version 
3. see error

**📸 Screenshots**
![image](https://github.com/astronomer/astro-cli/assets/5323384/13f05b96-864a-4d0f-9462-eb8ee487f97e)

https://astronomer.slack.com/archives/C055301MSPL/p1697560111548529?thread_ts=1695060035.699299&cid=C055301MSPL

**Comment by wolfier** [comment]
Zendesk Ticket: https://astronomer.zendesk.com/agent/tickets/31955

**Comment by kushalmalani** [comment]
This seems to be fixed. Closing it.
