### ISSUE TITLE
DEV- Image deploy erroring out with error message 

### ISSUE THREAD

**Issue by shri-astro** [astronomer/astro-cli#1420]
**Describe the bug**

Deploying the image from CLI is giving the below error 
Error message snippet:
```
ed9bb81c4c55: Pushed 
0e8b8fad567a: Pushing [=========================================>         ]   26.4MB/31.92MB
0e8b8fad567a: Pushed 
633f5bf471f7: Pushing [=====================>                             ]  34.633f5bf471f7: Pushed 
deploy-2023-10-18T09-30: digest: sha256:c4bc47ac99567b11252dbd2332fd3059a9e87437bf4c404ce4b44c766d570e7c size: 7835
Error: Cannot get digest for image: images.astronomer-dev.cloud/clibm2jyz000501m5tozxq2ea/clnvjhp1w201681uz0v9l6ehzj:deploy-2023-10-18T09-30
```
Command used : astro deploy -f
Deployment type : Standard Azure
Runtime version: 9.2.0

**What CLI Version did you experience this bug?**
Latest snapshot

**This CLI bug is related to which Astronomer Platform?**

- [ ] Astro

**What Operating System is the above CLI installed on?**
Mac M1 Pro

**Comment by kushalmalani** [comment]
This is a known issue on server side. Not a cli bug. Closing this ticket
