### ISSUE TITLE
`astro deploy` should always ask which deployment to deploy to

### ISSUE THREAD

**Issue by jedcunningham** [astronomer/astro-cli#1421]
- [x] I have checked that a similar [feature request](https://github.com/astronomer/astro-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**✍️ Is your feature request related to a problem? Please describe.**
Always ask me to which deployment I'd like to deploy to when I run a bare `astro deploy`. Especially if I'm using the wrong workspace accidentally, it can choose a deployment I really don't want to deploy to  💣.

```
$ astro deploy
Only one Deployment was found. Using the following Deployment by default: 
```

**🧩 Describe the solution you'd like**

Always ask me which deployment if I'm not using a specific deployment id. Even if there is just 1 deployment.

A `--no-confirm` flag could be added if we want to support the current behavior. Possibly also allow setting it via `.astro` too.

**💡 Additional context**

https://astronomer.slack.com/archives/CL44PA4DB/p1694797966688739

**Comment by sunkickr** [comment]
As of version 1.23 astro deploy will ask always ask users to select a deployment that are logged in as a user. You will not be asked to select a deployment if you are logged in with an API token/key. This is because we assume users are automating a process(ex: CI/CD) when using an API token/key
