### ISSUE TITLE
astro deployment airflow-variable has started giving 404 on all deployments

### ISSUE THREAD

**Issue by adammarples** [astronomer/astro-cli#1438]
**Describe the bug**

astro deployment airflow-variable list
astro deployment airflow-variable create
astro deployment connection list 
astro deployment connection create 

are raising errors on all deployments and using different versions of astro-cli

```
> astro deployment airflow-variable list --deployment-id clopi2lqt5982583oznk8kj25p5                   
Using an Astro API Token
Error: failed to decode response from API
```

```
astro deployment airflow-variable create --deployment-id clopi2lqt5982583oznk8kj25p5 --key 'a' --value 'b'
Using an Astro API Token
Creating variable a
Error: API error (404): 

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Airflow 404</title>
    <link rel="icon" type="image/png" href="https://cdn.astronomer.io/airflow/pin_32.5e56a23472220ff6b3b7.png">
  </head>
  <body>
    <div style="font-family: verdana; text-align: center; margin-top: 200px;">
      <img src="https://cdn.astronomer.io/airflow/pin_100.2da334cc389b24494079.png" width="50px" alt="pin-logo" />
      <h1>Airflow 404</h1>
      <p>Page cannot be found.</p>
      <a href="/">Return to the main page</a>
      <p>redact</p>
    </div>
  </body>
</html>
```

```
astro deployment connection list 
Using an Astro API Token
Select a Deployment
 #     DEPLOYMENT NAME     RELEASE NAME                     DEPLOYMENT ID                   DAG DEPLOY ENABLED     
 1     PR_TEST_DBT_72      infrared-transit-5268            clopi2lqt5982583oznk8kj25p5     true                   
 2     PR_TEST_DBT_78      ecliptical-spectroscope-6337     clopi2m575983653oznvbo7yp0t     true                   
 3     PR_TEST_DBT_79      galactic-frequency-3469          clopkk2rl6977921u4jhkq2ok6n     true                   

> 1
Error: failed to decode response from API
```

The API token itself is not an issure because other astro commands work fine, just airflow-variable and airflow-connection commands don't

**What CLI Version did you experience this bug?**

v1.17.0
v1.20.0

**This CLI bug is related to which Astronomer Platform?**

- [x] Astro
- [ ] Software
- [ ] None/Unknown

**What Operating System is the above CLI installed on?**

MacOS Sonoma 

**🪜 Steps To Reproduce**

run
astro deployment airflow-variable list
or any of the astro deployment airflow-variable group commands

**Comment by kushalmalani** [comment]
@adammarples  Fix is patched in release 1.20.1. Can you confirm if it looks good

**Comment by adammarples** [comment]
Thanks @kushalmalani the fix looks good but I'm not sure why v1.17.0 of the tool suddenly stopped working with v1 of the API?

**Comment by kushalmalani** [comment]
@adammarples The issue was on our side. We are transitioning our backend services and we had a regression. We wanted to fix forward because cli would have run into this again. Apologies for the inconvenience.

**Comment by adammarples** [comment]
Thanks for the quick fix
