### ISSUE TITLE
Users can no longer deploy only images

### ISSUE THREAD

**Issue by sunkickr** [astronomer/astro-cli#1445]
- [X] I have checked that a similar [feature request](https://github.com/astronomer/astro-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**✍️ Is your feature request related to a problem? Please describe.**

Due to a change in version 1.19.4 users can no longer push only images by leaving their DAG folder empty. They will receive a warning telling them that pushing an empty dags folder will erase their DAGs.

**🧩 Describe the solution you'd like**

`astro deploy --image`

New `--image` flag that allows users to deploy only an image

**🤔 Describe alternatives you've considered**

**Is your feature request specific to a particular Astronomer Platform?**

- [X] Astro
- [ ] Software
- [ ] None/Unknown

**💡 Additional context**

**Comment by kushalmalani** [comment]
This is fixed in 1.21.0
