### ISSUE TITLE
Astronomer deployment create arbitrary version

### ISSUE THREAD

**Issue by johnhoran** [astronomer/astro-cli#1449]
- [x] I have checked that a similar [feature request](https://github.com/astronomer/astro-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**✍️ Is your feature request related to a problem? Please describe.**

`astro deployment create --runtime-version` only supports a small number of versions.  This is an issue because we are working on a setup where deployments are created in staging for pull requests, however if my repo is currently using 9.4.0 then I can't create a deployment using 9.5.0 because (correct me if I'm wrong) I can't downgrade to an older version.  Currently I'm just hardcoding an older version 8.10.0 and then letting the deployment upgrade, but that feels brittle.  My alternative is to try deploying 9.4.0, then parse the error to figure out what I could deploy and upgrade from. 

**🧩 Describe the solution you'd like**

I would like to be able to create a deployment using any officially released version of astronomer.  

**🤔 Describe alternatives you've considered**

**Is your feature request specific to a particular Astronomer Platform?**

- [x] Astro
- [ ] Software
- [ ] None/Unknown

**💡 Additional context**

**Comment by sunkickr** [comment]
Are you saying `astro deployment create` won't let you create a deployment with a ` 9.4.0` runtime version? Are you using the latest CLI version? This may be fixed now in latest

**Comment by kushalmalani** [comment]
@johnhoran I believe this issue is fixed. If you have an existing deployment that is running on a runtime version we do allow you to create a new deployment with the same runtime version even though its deprecated. I am going to close this ticket, but feel free to re-open it if you continue to face an issue and we would be happy to look into it.
