### ISSUE TITLE
DEV -  Deployment update asks for deployment name even on provinding name at the command.

### ISSUE THREAD

**Issue by shri-astro** [astronomer/astro-cli#1466]
On performing the deployment update:
Even on providing the name of the deployment to be updated, the user is asked to choose the deployment to be updated.
Seems like a minor bug.

```
shrividyahegde@Hegde testlimits % astro deployment update -n "test_shri" --dag-deploy disable
Select a Deployment
 #     DEPLOYMENT NAME     RELEASE NAME              DEPLOYMENT ID                  DAG DEPLOY ENABLED     
 1     test-nightly        popular-ray-7134          clps3lbb9002b01l7fkg0bpic      false                  
 2     test perf           planetic-photon-1546      clps6zjuz00jq01lb6qqu6vp9      true                   
 3     test_shri           desolate-cluster-3100     clpsa6063121181cvbd0xeul9h     false                  

> 3

DAG-only deploys is already disabled for this deployment.
```

**What CLI Version did you experience this bug?**
1.21.0- pre-release version

**This CLI bug is related to which Astronomer Platform?**

- [ ] Astro

**What Operating System is the above CLI installed on?**
Mac OS

**Comment by kushalmalani** [comment]
-n flag is used to update the name of the deployment. You can pass the deploymentId if you dont want the select prompt - `astro deployment update [DEPLOYMENT-ID]`
