### ISSUE TITLE
Explicitly tell users in error logs when keys are expired

### ISSUE THREAD

**Issue by odaneau-astro** [astronomer/astro-cli#1469]
- [x] I have checked that a similar [feature request](https://github.com/astronomer/astro-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**✍️ Is your feature request related to a problem? Please describe.**
A user from Pepperstone complained that astro deploy stopped working for her recently.  
The error message did not explicitly mention that her API Token was expired.

> Im trying to get a first prod grade dag rolled up to astro, figuring things out,
I am facing an issue while pushing it and the log as follows,
Using an Astro API Token
Error: failed to find a valid workspace: failed to get current Workspace: current workspace context not set, you can switch to a workspace with
stro workspace switch WORKSPACEID
Usage:
  astro deploy DEPLOYMENT-ID [flags]
Any clue what the error here could be: Do i need to additionally specify the workspace, wouldnt it automatically be redirected to the workspace based on the deployment ID or am i wrong here? Thanks.
astro deploy --dags clni2cukx427177zewdxssirwmb

> Spent hours but figured out the issue, the api key which was configured previously has been expired 8 days ago :facepalm:
Error logging could have been better. 

**🧩 Describe the solution you'd like**

Add logs saying the key is expired when reporting errors

**🤔 Describe alternatives you've considered**

None

**Is your feature request specific to a particular Astronomer Platform?**

- [X] Astro
- [ ] Software
- [ ] None/Unknown

**💡 Additional context**

![image](https://github.com/astronomer/astro-cli/assets/111886489/bff0fd08-17ba-4540-b987-0c36ac4f5b50)

**Comment by sunkickr** [comment]
Also create an error for when the token does not exist

**Comment by vandyliu** [comment]
https://astronomer.slack.com/archives/CL44PA4DB/p1694772492568969
for some more context as well
