### ISSUE TITLE
Help flag not recognized on `astro dev run`

### ISSUE THREAD

**Issue by lzdanski** [astronomer/astro-cli#1475]
**Describe the bug**

When trying to access help info for the `astro dev run` command, the CLI automatically tries to execute `astro dev run`.  This occurs for both Astro and Software.

This behavior doesn't happen with any other commands. 

The following code examples has my directory/personal info redacted, but these are the error messages I receive. This is the only CLI command that required Docker to run in order to show the in-terminal help text.

**Software**

```
MacBook-Pro Projects % astro dev run -h
Error: this is not an Astro project directory.
Change to another directory or run astro dev init to turn your working directory into an Astro project
Usage:
  astro dev run [flags]

Examples:

# Create default admin user.
astro dev run users create -r Admin -u admin -e admin@example.com -f admin -l user -p admin


Flags:
  -h, --help   help for run

Global Flags:
      --verbosity string   Log level (debug, info, warn, error, fatal, panic (default "warning")

MacBook-Pro Projects % cd astro-1
MacBook-Pro astro-1 % astro dev run -h
Running: airflow -h
Error: error checking docker-compose status: Cannot connect to the Docker daemon at unix:///Users/.... Is the docker daemon running?
```

**Astro context**

```
MacBook-Pro astro-1 % astro dev run -h
Running: airflow -h
Error: error checking docker-compose status: Cannot connect to the Docker daemon at unix:///Users/... Is the docker daemon running?"
```

**What CLI Version did you experience this bug?**

1.21.0

**This CLI bug is related to which Astronomer Platform?**

- [x] Astro
- [x] Software
- [ ] None/Unknown

**What Operating System is the above CLI installed on?**

**🪜 Steps To Reproduce**

1. Do not have Docker running yet (this is the only thing I can think of having an impact, I noticed after I saw the errors)
2. In software context, run `astro dev run -h` or `astro dev run --help`
3. In Astro context, run `astro dev run -h` or `astro dev run --help`

**📸 Screenshots**

N/A

**Comment by kushalmalani** [comment]
@lzdanski With astro dev run, we actually run airflow cli underneath it. So the idea is we want to show help commands from the airflow-cli since that help menu is more useful. 

if you start an airflow project and run  the same command you should see the help menu

Do the following steps:

1. astro dev start
2. astro dev run -h

This should be the output you see

```
[2024-01-02T16:19:34.825+0000] {plugin.py:32} WARNING - Astro managed secrets backend is disabled
Usage: airflow [-h] GROUP_OR_COMMAND ...

Positional Arguments:
  GROUP_OR_COMMAND

    Groups
      config         View configuration
      connections    Manage connections
      dags           Manage DAGs
      db             Database operations
      jobs           Manage jobs
      pools          Manage pools
      providers      Display providers
      roles          Manage roles
      tasks          Manage tasks
      users          Manage users
      variables      Manage variables

    Commands:
      cheat-sheet    Display cheat sheet
      dag-processor  Start a standalone Dag Processor instance
      info           Show information about current Airflow and environment
      kerberos       Start a kerberos ticket renewer
      plugins        Dump information about loaded plugins
      rotate-fernet-key
                     Rotate encrypted connection credentials and variables
      scheduler      Start a scheduler instance
      standalone     Run an all-in-one copy of Airflow
      sync-perm      Update permissions for existing roles and optionally DAGs
      triggerer      Start a triggerer instance
      version        Show the version
      webserver      Start a Airflow webserver instance
```

**Comment by kushalmalani** [comment]
@lzdanski Going to close this. Let me know if you have questions
