### ISSUE TITLE
Ambiguous Error Message

### ISSUE THREAD

**Issue by stuart23** [astronomer/astro-cli#1500]
This error message is not descriptive enough. For example, if `GetWorkspaces` returns `ErrNoShortName` then the error is not due to an incorrect workspace name.

https://github.com/astronomer/astro-cli/blob/3116abad04e531714807437a8f61b1c89582d54e/cloud/workspace/workspace.go#L142

**Comment by sunkickr** [comment]
we have removed ErrNoShortName. Users should get a more descriptive error now
