### ISSUE TITLE
Docs Fix: Change wording on deploy message

### ISSUE THREAD

**Issue by virajmparekh** [astronomer/astro-cli#154]
When you go to deploy through the CLI:
```
virajparekh@orbiter:~/Code/Astronomer/test_install/test_deploy$ astro airflow deploy -f
Authenticated to astronomer.cloud 

Select which airflow deployment you want to deploy to:
 #    RELEASE NAME                  WORKSPACE                     DEPLOYMENT UUID                                   
 1    true-aphelion-2649            Astro Demo                    ee4ba179-8b12-45dd-a0e2-867e588c25ae 

```

I think `RELEASE NAME` should be changed to `DEPLOYMENT NAME` - we do not refer to airflow instances as releases in any of our other docs.

**Comment by schnie** [comment]
Yep, makes sense, lets do it.

**Comment by benjamingregory** [comment]
@vparekh94 I agree this is the best move but wanted to get @schnie's approval before we deviated from the API naming convention.
