### ISSUE TITLE
Clean up error messages when not authenticated

### ISSUE THREAD

**Issue by vparekh94** [astronomer/astro-cli#161]
As a user, my CLI login might have expired when I go to do a deploy. 

Currently, I get an error like:
`Error: Requester not authorized to execute “workspaces”`

and similar errors when I try to list/switch workspaces.

The error message should be expanded to something like `Try logging in again astro auth login astronomer.cloud (or your base domain)`

**Comment by andriisoldatenko** [comment]
@schnie @ryw I think I fixed it in https://github.com/astronomer/astro-cli/commit/49d4ba52a10520b43e08516c242555a240c405f8

**Comment by schnie** [comment]
Yep, guess we forgot about this issue :)
