### ISSUE TITLE
Airflow UI URL after `astro deploy` is broken

### ISSUE THREAD

**Issue by jessicaschueler** [astronomer/astro-cli#1623]
**Describe the bug**

The URL printed after running `astro deploy` points to an API endpoint instead of the Astro homepage. 

```
Successfully pushed image to Astronomer registry. Navigate to the Astronomer UI for confirmation that your deploy was successful.

 Access your Deployment:

 Deployment View: https://cloud.astronomer.io/clilt7vco00a601kk5fz65ob1/deployments/clv44y0al024c01pl5dg1x9fd/overview
 Airflow UI: https://org-astronomer-cre.astronomer.run/ddg1x9fd/api/v1
```

**What CLI Version did you experience this bug?**

Astro 1.25.0

**This CLI bug is related to which Astronomer Platform?**

- [x] Astro
- [ ] Software
- [ ] None/Unknown

**What Operating System is the above CLI installed on?**

**🪜 Steps To Reproduce**

1. Deploy to Astro

**Comment by kushalmalani** [comment]
@jessicaschueler This has been fixed - https://github.com/astronomer/astro-cli/pull/1619 and is scheduled to release as part of 1.26.0 Wednesday next week. I am going to close this ticket. Feel free to re-open if you still have follow up questions
