### ISSUE TITLE
Latest CLI versions breaks when trying to create a deployment with the same name as in a different Workspace

### ISSUE THREAD

**Issue by AstroSucheta** [astronomer/astro-cli#1644]
**Describe the bug**

On CLI version 1.25/1.26 when trying to create deployment with the same name as the one existing in a different name space, it fails with the following error 

 Error: deployment: default_queue_2 already exists: use deployment update --deployment-file template.yaml instead

However we are still able to create it using UI

**What CLI Version did you experience this bug?**
1.25/1.26

**This CLI bug is related to which Astronomer Platform?**
Astro 

**What Operating System is the above CLI installed on?**
All
**🪜 Steps To Reproduce*

 1. Create a deployment in workspace A
 2. Inspect the deployment to generate template. astro deployment inspect <deployment_id> (or create your own sample template and keep the name same as earlier)
 3. Modify the workspace name and remove metadata in the template
 4. Switch to the workspace B
 5. Run astro deployment create --deployment-file template.yaml

**📸 Screenshots**

**Comment by kushalmalani** [comment]
This has been fixed and will be released as part of 1.27.0 next week
