### ISSUE TITLE
`astro login` fails on callback "This site can’t provide a secure connection"

### ISSUE THREAD

**Issue by felipecaldas** [astronomer/astro-cli#1649]
Hi,

I have Astro CLI installed in Windows 11 via winget. When attempting to run `astro login`, my a new Chrome tab opens, I then login with my Google account and the call back fails:

![image](https://github.com/astronomer/astro-cli/assets/3864696/1c90f42d-ebe4-4481-bcda-3217c799e57f)

The callback URL is: https://localhost:12345/callback?code=<redacted>

Any suggestions on how to fix this? Thank you

**Comment by kushalmalani** [comment]
What CLI version are you using? 
Do you get any error in your terminal/wherever you triggered astro login from?

**Comment by felipecaldas** [comment]
Hi,

I am on 1.26.0. When trying to update with winget, this is what I am getting:

> 
> PS C:\Projects\customers\anz-nz> astro version  
> 
> A newer version of Astro CLI is available: 1.27.1
> Please see https://docs.astronomer.io/astro/cli/install-cli#upgrade-the-cli for information on how to update the Astro CLI
> 
> If you don't want to see this message again run 'astro config set -g upgrade_message false'
> 
> Astro CLI Version: 1.26.0
> PS C:\Projects\customers\anz-nz> winget install -e --id Astronomer.Astro
> Found an existing package already installed. Trying to upgrade the installed package...
> No available upgrade found.
> No newer package versions are available from the configured sources.
> PS C:\Projects\customers\anz-nz> astro version
> 
> A newer version of Astro CLI is available: 1.27.1
> Please see https://docs.astronomer.io/astro/cli/install-cli#upgrade-the-cli for information on how to update the Astro CLI
> 
> If you don't want to see this message again run 'astro config set -g upgrade_message false'
> 
> Astro CLI Version: 1.26.0

Not sure why it's not upgrading using winget.

Next, I went to WSL/Ubuntu and was able to upgrade to 1.27.1. But then I get exactly the same error as reported here:

![image](https://github.com/astronomer/astro-cli/assets/3864696/291922ef-ac8a-419a-b1a4-de1d9a50652c)

**Comment by felipecaldas** [comment]
I uninstalled astro with winget, then downloaded the .exe file - version 1.27.1 - and tried to login using that executable and got exactly same error again.
Could this be a Chrome problem? I haven't tried with a different browser. It seems to be that the non-SSL callback URL is not getting accepted by Chrome

**Comment by felipecaldas** [comment]
I am happy to report that it has worked on Firefox - but not on Chrome and Vivaldi.
