### ISSUE TITLE
Stay logged in after switching clusters

### ISSUE THREAD

**Issue by vparekh94** [astronomer/astro-cli#169]
As a user, I might be switching between several Astronomer clusters. Right now, if I am logged into `Cluster A`, switch to `Cluster B` and login, and then try to switch back to `Cluster A` - I will have been logged out of `Cluster A.`  

The preferred behavior would be to stay logged into a cluster until I explicitly logout or the token expires, not automatically getting logged out when I run `astro cluster switch`

**Comment by schnie** [comment]
@andriisoldatenko what do you think about this one? Does it seem feasible, given our current structure?

**Comment by andriisoldatenko** [comment]
@schnie it works for me as is on master:
For instance:
Steps to reproduce:
- `astro auth login datarouter.ai` - OK
- `astro auth login alpha.datarouter.ai` - OK
- Switch to prod back
```
cluster switch
#     NAME
1     datarouter.ai
2     localhost
3     http://localhost
4     alpha.datarouter.ai

> 1
 CLUSTER                             WORKSPACE
 datarouter.ai                       cjsu4oyei00r80d86b0lsprih
```
- Do some actions:
```
go run main.go deployment list
 NAME       DEPLOYMENT NAME          ASTRO      DEPLOYMENT ID
 andrii     explosive-space-6550     v0.7.5     cjsugbfzf00t80d8625tzxmiu
```
- Check that you have 2 JWT tokens inside `~/.astro/config.yaml` for `alpha_datarouter_ai` and `datarouter_ai`.
Please let me know if you need something else.

**Comment by andriisoldatenko** [comment]
As you can see in source code, we are not touching any logout code.
workspace/workspace.go:187

**Comment by andriisoldatenko** [comment]
@schnie could you please take another look on master?

**Comment by andriisoldatenko** [comment]
cc @vparekh94

**Comment by schnie** [comment]
I think this is fine too. Closing now.
