### ISSUE TITLE
Fail with a helpful message if the user tries to push an image with a modified entrypoint

### ISSUE THREAD

**Issue by MatrixManAtYrService** [astronomer/astro-cli#1725]
- [x ] I have checked that a similar [feature request](https://github.com/astronomer/astro-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**✍️ Is your feature request related to a problem? Please describe.**

[nova-20240927-earthbound-bolometer](https://astronomer.slack.com/archives/C07PC2CNAG5) was caused by a user who pushed an image with a modified entrypoint.  The modified entrypoint ran `/bin/bash` at PID 1, rather than `tini`.  This prevented signals from propagating to subprocesses correctly, which prevented worker pods from being cleaned up.  The lingering worker pods was a cost that we'd rather not have paid.

**🧩 Describe the solution you'd like**

I would like users to be prevented from pushing images with modified entrypoints.  Perhaps we could inspect the base image and inspect the final image and assert that the entrypoints are equal before pushing.

**Is your feature request specific to a particular Astronomer Platform?**

- [ x] Astro
- [ ] Software
- [ ] None/Unknown

**Comment by melugoyal** [comment]
copying from slack:

> the problem with doing it in the CLI is we would break customers who are already overriding the entrypoint but either doing it correctly, or haven't messed things up enough for us to notice so if we can just override the entrypoint to be correct at runtime via the operator (https://github.com/astronomer/airflow-operator/issues/1922), that is better.
