### ISSUE TITLE
Prevent updateDeployment call if docker push fails

### ISSUE THREAD

**Issue by schnie** [astronomer/astro-cli#173]
Based on a recent issue, it seems like we are not looking at the result of the `docker push`, before making the request to houston `updateDeployment`. We should prevent the houston call if the push fails, otherwise it can result in `ImagePullBackoff` errors in kube.

**Comment by schnie** [comment]
@benjamingregory you think you'll be able to knock this out for v0.8? Adding it to the v0.8 queue.

**Comment by benjamingregory** [comment]
@schnie On it.

**Comment by benjamingregory** [comment]
Closing as unrelated to CLI -- error likely coming from Houston.
