### ISSUE TITLE
Parse partial Airflow versions

### ISSUE THREAD

**Issue by BasPH** [astronomer/astro-cli#1732]
**Describe the bug**

Providing only a major/minor Airflow version fails (with an obfuscated error), and defaults to a rather old Airflow version:
```
$ astro dev init --airflow-version 2.9
WARNING! There was a network issue getting the latest Astro Runtime image. Your Dockerfile may not contain the latest version
Initializing Astro project
Pulling Airflow development files from Astro Runtime 5.0.1
```

Turns out you have to specify the full major/minor/patch version:
```
$ astro dev init --airflow-version 2.9.3
Initializing Astro project
Pulling Airflow development files from Astro Runtime 11.11.0
```

I would expect different behaviour, e.g. selecting the latest version within Airflow 2.9.*, or a meaningful message that the version cannot be found, or a list of Airflow versions to choose from.

**What CLI Version did you experience this bug?**
1.29.0

**This CLI bug is related to which Astronomer Platform?**

- [ ] Astro
- [ ] Software
- [ ] None/Unknown

**What Operating System is the above CLI installed on?**

**🪜 Steps To Reproduce**

**📸 Screenshots**

**Comment by robshea-astro** [comment]
To be addressed in #1733
