### ISSUE TITLE
Fix workspace switch workflow

### ISSUE THREAD

**Issue by schnie** [astronomer/astro-cli#178]
Right now when a user logs into a new cluster, we don't update the active workspace, which leads to a confusing UX. Listing deployments or doing deploys appears broken, until the user realizes they need to switch to an active workspace in the active cluster. We need to fix this workflow to help users.

Maybe we could auto switch the workspace to the first workspace or default workspace in the new cluster for them, or something like that.

**Comment by andriisoldatenko** [comment]
As confirmed in slack:
- attempt to use the last used workspace, unless it's been deleted, then show the menu to select.
