### ISSUE TITLE
Show friendly deployment names

### ISSUE THREAD

**Issue by schnie** [astronomer/astro-cli#179]
Currently we only show the release name for a deployment. We should also show the user-chosen friendly name for `astro deployment list` and `astro airflow deploy` commands.

**Comment by andriisoldatenko** [comment]
@schnie do you mean deployment label?
```
{
  "data": {
    "deployments": [
      {
        "id": "cjsugbfzf00t80d8625tzxmiu",
        "type": "airflow",
        "label": "andrii",
        "releaseName": "explosive-space-6550",
        "workspace": {
          "id": "cjsu4oyei00r80d86b0lsprih"
        },
        "deployInfo": {
          "latest": null,
          "next": "cli-1"
        },
        "version": "0.7.5",
        "createdAt": "2019-03-04T14:40:16.299Z",
        "updatedAt": "2019-03-04T14:40:16.299Z"
      }
    ]
  }
}
```

**Comment by andriisoldatenko** [comment]
should i add column "label" in the end?
```
go run main.go  deployment list
 NAME       DEPLOYMENT NAME          ASTRO      DEPLOYMENT ID
 andrii     explosive-space-6550     v0.7.5     cjsugbfzf00t80d8625tzxmiu
```

**Comment by schnie** [comment]
@andriisoldatenko actually now that I think about this, we're already showing it as the first column.

@vparekh94 I'm not sure where this one came from. Looks like we already do this. Am I forgetting or thinking of something else?

Going to close it for now, reopen if you think of something.

**Comment by vparekh94** [comment]
Hmm - yeah looks like this is already there in v0.8 CLI, in v0.7 it looks
like this:

```
virajparekh@orbiter:~/Code/Astronomer/airflow-example-dags$ astro airflow
deploy -f
Authenticated to demo.datarouter.ai

Select which airflow deployment you want to deploy to:
 #    RELEASE NAME                  WORKSPACE
 DEPLOYMENT UUID
 1    advanced-waning-7376          Viraj Parekh's Workspace
cjsp547zs001x0b13v4lz6gic
 2    elementary-phase-9414         Viraj Parekh's Workspace
cjspeysmv00kf0b1336ei1snj

>
```

Must've been looking for bugs on the older version. We are good :)

**Comment by schnie** [comment]
Oh, maybe @benjamingregory fixed this one or something. :man_shrugging:
