### ISSUE TITLE
Touch up astro deployment update

### ISSUE THREAD

**Issue by schnie** [astronomer/astro-cli#181]
astro deployment update should list possible flags:

```
virajparekh@orbiter:~$ astro de update
Error: must specify a deployment ID and at least one attribute to update.
Usage:
  astro deployment update [flags]

Aliases:
  update, up

Examples:

	astro deployment update UUID label=Production-Airflow

Flags:
  -h, --help   help for update

Global Flags:
      --workspace-id string   workspace assigned to deployment
```

I'm not entirely sure what we can even do with this command right now. If it does work, we may just need to document it better.

**Comment by andriisoldatenko** [comment]
here we do mutation https://github.com/astronomer/astro-cli/blob/master/deployment/deployment.go#L110 and https://github.com/astronomer/astro-cli/blob/master/houston/queries.go#L85-L100, not sure what need to fix :)

**Comment by andriisoldatenko** [comment]
Most magic code here is `args`, which we send to payload, need to dig into huston code.
and than may be here ->
https://github.com/astronomer/houston-api/blob/master/src/resolvers/mutation/update-deployment/index.js#L49-L50

**Comment by andriisoldatenko** [comment]
@schnie please take a look ^

**Comment by schnie** [comment]
@andriisoldatenko How would someone use the command now? Does it work?

Is it a matter of passing args like: `astro deployment update --name new-name --version some-version`?

**Comment by schnie** [comment]
@andriisoldatenko how do you specify the payload to the mutation using the CLI now? Does it work currently?

**Comment by andriisoldatenko** [comment]
@schnie @vparekh94 you can try, but I also not sure what we can pass as key/value
```
astro deployment update UUID key=value key1=value2
```
For instance:
```
$ astro deployment update cjt7gwnl20m4j0b08vmc1fm92 k=andrii1233333333
 NAME       DEPLOYMENT NAME                  ASTRO     DEPLOYMENT ID
 andrii     spherical-constellation-8941     0.7.5     cjt7gwnl20m4j0b08vmc1fm92

 Successfully updated deployment
$ astro deployment list
 NAME       DEPLOYMENT NAME                  ASTRO      DEPLOYMENT ID
 andrii     spherical-constellation-8941     v0.7.5     cjt7gwnl20m4j0b08vmc1fm92
```
