### ISSUE TITLE
Show more descriptive error message when token expires

### ISSUE THREAD

**Issue by schnie** [astronomer/astro-cli#182]
Right now, when the JWT expires, the CLI will just report that I do not have permission for that action. We should prompt them to log in again.

**Comment by andriisoldatenko** [comment]
@schnie could you please provide exact new error message wrapper?
```
astro workspace list
Error: ???please login: astro auth login
exit status 1
```

**Comment by schnie** [comment]
Hmm, how about something like `Your token has expired. Please log in again.`

**Comment by andriisoldatenko** [comment]
@schnie please take another look.
