### ISSUE TITLE
Add support for streaming logs

### ISSUE THREAD

**Issue by schnie** [astronomer/astro-cli#191]
With v0.8.0, we added support in Houston for querying and streaming logs from Elasticsearch. With v0.9.0, we should follow up with the same support in our CLI.

A rough idea for commands:
`astro airflow logs` - Run a query for last 5 minutes of logs for scheduler by default
`astro airflow logs (scheduler|webserver|workers)` - Run query for last 5 minutes of logs and output
`astro airflow logs (scheduler|webserver|worker) -f` - Run query for last 5 minutes of logs, output, then subscribe to more.
`astro airflow logs (scheduler|webserver|workers) --follow --search "some search terms"` - Run query for last 5 min and specify search term, and subscribe to more.

@andriisoldatenko what do you think about this one? Would require a standard GraphQL query, which we already do for other things, plus the ability to subscribe over websockets, like Orbit does.

@benjamingregory @vparekh94 feel free to add any thoughts

**Comment by vparekh94** [comment]
@schnie I'm so down for this idea, would be a huge value add to our platform. 

Down the road, do you think that we can use other standard queries to get other stats straight from the CLI? Something like number of running tasks, or  summary of tasks from the last hour?

**Comment by schnie** [comment]
Yep, I think we can bake that into the data we're gathering in Prometheus and expose it through Houston, the same stuff we'll be showing in Orbit.

**Comment by andriisoldatenko** [comment]
@schnie please correct if you can see any UX issues or typos?
```
A longer description that spans multiple lines and likely contains examples
and usage of using your command. For example:

astro logs webserver

Usage:
  astro logs [flags]
  astro logs [command]

Aliases:
  logs, log, l

Available Commands:
  scheduler   airflow scheduler logs
  webserver   airflow webserver logs
  workers     airflow workers logs

Flags:
  -f, --follow   Subscribe to watch more logs.
  -h, --help     help for logs
  -s, --search   Search term inside logs

Use "astro logs [command] --help" for more information about a command.
```

**Comment by schnie** [comment]
LGTM :+1:
