### ISSUE TITLE
Error deploying with 0.8.0-rc.1

### ISSUE THREAD

**Issue by edbizarro** [astronomer/astro-cli#192]
After run `astro upgrade`

```
❯ curl -sL https://install.astronomer.io | sudo bash
astronomer/astro-cli: checking GitHub for latest tag
astronomer/astro-cli: found version: 0.8.0-rc.1 for v0.8.0-rc.1/linux/amd64
astronomer/astro-cli: downloading https://github.com/astronomer/astro-cli/releases/download/v0.8.0-rc.1/astro_0.8.0-rc.1_linux_amd64.tar.gz
astronomer/astro-cli: downloading https://github.com/astronomer/astro-cli/releases/download/v0.8.0-rc.1/astro_0.8.0-rc.1_checksums.txt
astronomer/astro-cli: verifying checksums
astronomer/astro-cli: installed as /usr/local/bin/astro
```

I keep getting this error when trying to deploy

```
❯ astro airflow deploy
Error: API error (400): {"errors":[{"message":"Cannot query field \"id\" on type \"Workspace\". Did you mean \"uuid\"?","locations":[{"line":8,"column":4}],"type":"GraphQLError","timestamp":1552167634298}]}
2019/03/09 18:40:34 API error (400): {"errors":[{"message":"Cannot query field \"id\" on type \"Workspace\". Did you mean \"uuid\"?","locations":[{"line":8,"column":4}],"type":"GraphQLError","timestamp":1552167634298}]}
```

**Comment by schnie** [comment]
Hey @edbizarro, we're getting ready to cut our latest release but we have a small issue with our standard install script. It currently pulls the latest build no matter what, including pre-release versions. We'll have that fixed up soon, but until then you can just specify the version explicitly. Our latest stable release is 0.7.5, so `curl -sSL https://install.astronomer.io | sudo bash -s -- v0.7.5` should get you up and running.

**Comment by edbizarro** [comment]
Thanks @schnie 

Actually, with pre-release version (v0.8.0-alpha.8) everything works fine, but the v0.8.0-rc.1, does not.

I switched back to v0.8.0-alpha.8, thanks!
