### ISSUE TITLE
Astro CLI for Windows error authenticating

### ISSUE THREAD

**Issue by andrewhharmon** [astronomer/astro-cli#211]
when using the windows cli, after running `astro auth login` and providing the token, I get the following error

```Failed to authenticate to the registry, this can occur when registry is offline. Until authenticated you will not be able to push new images to your Airflow clusters```

**Comment by ryw** [comment]
@andriisoldatenko have you looked at this yet?

**Comment by andriisoldatenko** [comment]
@ryw i'll take a look today
