### ISSUE TITLE
Astro airflow init uses wrong Airflow version

### ISSUE THREAD

**Issue by vparekh94** [astronomer/astro-cli#220]
The 0.9.2 CLI creates a Dockerfile that references a non-existent Airflow image:
```
virajparekh@orbiter:~/Code/Astronomer/Other/new$ astro version
Astro CLI Version: 0.9.0 
Git Commit: 62dc9de82d07fa64d8216a835465074db964af4a
virajparekh@orbiter:~/Code/Astronomer/Other/new$ astro airflow init
Initialized empty astronomer project in /home/virajparekh/Code/Astronomer/Other/new
virajparekh@orbiter:~/Code/Astronomer/Other/new$ ls
airflow_settings.yaml  dags  Dockerfile  include  packages.txt  plugins  requirements.txt
virajparekh@orbiter:~/Code/Astronomer/Other/new$ cat Dockerfile 
FROM astronomerinc/ap-airflow:0.9.0-1.10.2-onbuild
```

The correct image is tag is `0.9.0-1.10.3`:

![image](https://user-images.githubusercontent.com/19679395/58049439-dd14ba00-7b1a-11e9-8972-e08ecd9cf647.png)

**Comment by schnie** [comment]
Good catch. Should be a quick bump in the code to fix for now. We really need to sort out our airflow / platform versioning issues between the CLI, the Dockerfile and the platform.

cc @ryw

**Comment by andriisoldatenko** [comment]
@schnie fixed.
