### ISSUE TITLE
All command return error

### ISSUE THREAD

**Issue by edbizarro** [astronomer/astro-cli#232]
All commands are return this error:

```
~/workspace/pdh/data/maestro master 16s
maestro_venv ❯ astro de list
Error: API error (400): {"errors":[{"message":"Cannot query field \"id\" on type \"Deployment\". Did you mean \"uuid\"?","locations":[{"line":12,"column":4}],"type":"GraphQLError","timestamp":1560137708309},{"message":"Cannot query field \"id\" on type \"Workspace\". Did you mean \"uuid\"?","locations":[{"line":17,"column":5}],"type":"GraphQLError","timestamp":1560137708309}]}
2019/06/10 00:35:08 API error (400): {"errors":[{"message":"Cannot query field \"id\" on type \"Deployment\". Did you mean \"uuid\"?","locations":[{"line":12,"column":4}],"type":"GraphQLError","timestamp":1560137708309},{"message":"Cannot query field \"id\" on type \"Workspace\". Did you mean \"uuid\"?","locations":[{"line":17,"column":5}],"type":"GraphQLError","timestamp":1560137708309}]}

```

Tested with `v0.8.0`, `v0.8.2` and `v0.9.0` with no luck

I'm on Arch Linux

**Comment by edbizarro** [comment]
I've already [had this error before](https://github.com/astronomer/astro-cli/issues/192), but on a specific command (deploy) and version, but now It's on all commands return

**Comment by vparekh94** [comment]
hey @edbizarro are you a cloud customer or an enterprise customer?

**Comment by edbizarro** [comment]
I'm a cloud customer, thanks for the tip, i'll test with that version

**Comment by edbizarro** [comment]
With `v0.7.5-2` everything is working now, thanks.

**Comment by vparekh94** [comment]
Awesome! Glad to help!

In the future, you'll get a much faster response if you contact support@astronomer.io - our entire support team will get pinged there - we'll then escalate to this repo it's not a quick fix :)
