### ISSUE TITLE
astro airflow start error, docker manifest not found

### ISSUE THREAD

**Issue by TZubiri** [astronomer/astro-cli#239]
```
:~/astronomer$ sudo astro airflow start
Env file ".env" found. Loading...
Sending build context to Docker daemon  11.78kB
Step 1/1 : FROM astronomerinc/ap-airflow:0.7.5-2-1.9.0-onbuild
manifest for astronomerinc/ap-airflow:0.7.5-2-1.9.0-onbuild not found
Error: command 'docker build -t astronomer/airflow:latest failed: failed to execute cmd: exit status 1

```
Running Ubuntu 18 x86
Downloaded astro version 0.7.5-2 

Upgrading via the command issued by astro upgrade didn't help
```

Env file ".env" found. Loading...
Sending build context to Docker daemon  12.29kB
Step 1/1 : FROM astronomerinc/ap-airflow:0.9.0-1.10.2-onbuild
manifest for astronomerinc/ap-airflow:0.9.0-1.10.2-onbuild not found
Error: command 'docker build -t astronomer_882a0e/airflow:latest failed: failed to execute cmd: exit status 1
2019/06/18 18:42:54 command 'docker build -t astronomer_882a0e/airflow:latest failed: failed to execute cmd: exit status 1
```
 
This is a bad welcome to astronomer :(

**Comment by vparekh94** [comment]
Hi there! This is a known bug right now that's been fixed in our next release.

If you are using the latest version of the CLI (currently only for enterprise users), change the FROM line to:
`FROM astronomerinc/ap-airflow:0.9.0-1.10.3-onbuild`

If you are using Cloud, use:
`FROM astronomerinc/ap-airflow:0.7.5-1.10.1-onbuild`

**Comment by vparekh94** [comment]
hey @TZubiri were you able to try any of those solutions? Would love to close this out.

**Comment by TZubiri** [comment]
This worked. Thanks!

**Comment by TZubiri** [comment]
Whoops, faced another error.
~/astronomer$ sudo astro airflow start
Env file ".env" found. Loading...
Sending build context to Docker daemon  12.29kB
Step 1/1 : FROM astronomerinc/ap-airflow:0.7.5-1.10.1-onbuild
# Executing 5 build triggers
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> 357d4d78a10e
Successfully built 357d4d78a10e
Successfully tagged astronomer_882a0e/airflow:latest
Pulling postgres (postgres:10.1-alpine)...
INFO[0000] [0/3] [postgres]: Starting                   
panic: runtime error: index out of range

goroutine 11 [running]:
github.com/astronomer/astro-cli/vendor/github.com/Nvveen/Gotty.readTermInfo(0xc0000247c0, 0x1e, 0x0, 0x0, 0x0)
	/go/src/github.com/astronomer/astro-cli/vendor/github.com/Nvveen/Gotty/gotty.go:232 +0xd12
github.com/astronomer/astro-cli/vendor/github.com/Nvveen/Gotty.OpenTermInfo(0xc0000240e5, 0xe, 0xc0000240e5, 0xe, 0x0)
	/go/src/github.com/astronomer/astro-cli/vendor/github.com/Nvveen/Gotty/gotty.go:45 +0x276
github.com/astronomer/astro-cli/vendor/github.com/docker/docker/pkg/jsonmessage.DisplayJSONMessagesStream(0xc1dd40, 0xc0003545c0, 0xc1df40, 0xc00000e020, 0x2, 0x1, 0x0, 0x4, 0x0)
	/go/src/github.com/astronomer/astro-cli/vendor/github.com/docker/docker/pkg/jsonmessage/jsonmessage.go:245 +0x549
github.com/astronomer/astro-cli/vendor/github.com/docker/libcompose/docker/image.PullImage(0xc2d1c0, 0xc0000260a8, 0x7f3c5340d3e8, 0xc0002ec380, 0xc000452da8, 0x8, 0xc25940, 0xc00000e4d8, 0xc000462f40, 0x14, ...)
	/go/src/github.com/astronomer/astro-cli/vendor/github.com/docker/libcompose/docker/image/image.go:83 +0x4ec
github.com/astronomer/astro-cli/vendor/github.com/docker/libcompose/docker/service.(*Service).Pull(0xc0004720a0, 0xc2d1c0, 0xc0000260a8, 0xc0002ec380, 0xc000462f40)
	/go/src/github.com/astronomer/astro-cli/vendor/github.com/docker/libcompose/docker/service/service.go:629 +0x119
github.com/astronomer/astro-cli/vendor/github.com/docker/libcompose/docker/service.(*Service).ensureImageExists(0xc0004720a0, 0xc2d1c0, 0xc0000260a8, 0x1110000, 0x0, 0x0)
	/go/src/github.com/astronomer/astro-cli/vendor/github.com/docker/libcompose/docker/service/service.go:157 +0x2b8
github.com/astronomer/astro-cli/vendor/github.com/docker/libcompose/docker/service.(*Service).Up(0xc0004720a0, 0xc2d1c0, 0xc0000260a8, 0xc000000000, 0x8, 0x0)
	/go/src/github.com/astronomer/astro-cli/vendor/github.com/docker/libcompose/docker/service/service.go:237 +0xd0
github.com/astronomer/astro-cli/vendor/github.com/docker/libcompose/project.(*Project).Up.func1.1(0xc3a1c0, 0xc0004720a0, 0xc000452da8, 0x8)
	/go/src/github.com/astronomer/astro-cli/vendor/github.com/docker/libcompose/project/project_up.go:17 +0x68
github.com/astronomer/astro-cli/vendor/github.com/docker/libcompose/project.(*serviceWrapper).Do(0xc000102310, 0xc000208990, 0x4, 0x6, 0xc000080fa0)
	/go/src/github.com/astronomer/astro-cli/vendor/github.com/docker/libcompose/project/service-wrapper.go:101 +0x11a
github.com/astronomer/astro-cli/vendor/github.com/docker/libcompose/project.(*Project).Up.func1(0xc000102310, 0xc000208990)
	/go/src/github.com/astronomer/astro-cli/vendor/github.com/docker/libcompose/project/project_up.go:16 +0xad
created by github.com/astronomer/astro-cli/vendor/github.com/docker/libcompose/project.(*Project).startService
	/go/src/github.com/astronomer/astro-cli/vendor/github.com/docker/libcompose/project/project.go:448 +0x4f5
`

Note, 'sudo docker run postgres:10.1-alpine' works without issue.

**Comment by vparekh94** [comment]
Can you try running `docker pull  postgres:10.1-alpine` ? That error looks like its on pulling the postgres image

**Comment by TZubiri** [comment]
Yep, 


> Note, 'sudo docker run postgres:10.1-alpine' works without issue.

**Comment by TZubiri** [comment]
Maybe this has something to do with me uisng the version 0.9 of the cli with the docker image 0.7.5?
How can I uninstall the cli so I can reinstall the old version?

**Comment by TZubiri** [comment]
> astro airflow start
Env file ".env" found. Loading...
Sending build context to Docker daemon  12.29kB
Step 1/1 : FROM astronomerinc/ap-airflow:0.7.5-1.10.1-onbuild
# Executing 5 build triggers
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> 357d4d78a10e
Successfully built 357d4d78a10e
Successfully tagged astronomer_882a0e/airflow:latest
INFO[0000] [0/3] [postgres]: Starting                   
INFO[0001] [1/3] [postgres]: Started                    
INFO[0001] [1/3] [scheduler]: Starting                  
INFO[0002] [2/3] [scheduler]: Started                   
INFO[0002] [2/3] [webserver]: Starting                  
INFO[0004] [3/3] [webserver]: Started                   
Airflow Webserver: http://localhost:8080/admin/
Postgres Database: localhost:5432/postgres

I tried again and it worked correctly :S . It seems like a heisenbug. Let me know if you would like me to share any log files or system info.
