### ISSUE TITLE
`astro airflow deploy <non-existent deployment name>` returns "Error parsing reference..."

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/astro-cli#247]
**Problem**

If a user runs `astro airflow deploy` followed by a non-existent release name (e.g. `dev` in this example ), the CLI returned the following error:

```
$ astro airflow deploy dev -f
Deploying: dev
dev/airflow
Building image...
Sending build context to Docker daemon  11.78kB
Step 1/1 : FROM astronomerinc/ap-airflow:0.7.5-1.10.1-onbuild
# Executing 5 build triggers
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> fac83ad0b2d8
Successfully built fac83ad0b2d8
Successfully tagged dev/airflow:latest
Error parsing reference: "registry.astronomer.cloud/dev/airflow:" is not a valid repository/tag: invalid reference format
Error: command 'docker tag dev/airflow:latest registry.astronomer.cloud/dev/airflow:' failed: failed to execute cmd: exit status 1
```

_Just_ running `astro airflow deploy` (no deployment name) gives this error:

```
$ astro deployment list
 NAME     RELEASE NAME     ASTRO     DEPLOYMENT ID     
$ astro airflow deploy -f
Error: No airflow deployments found
```

**Potential Solution**

Is there a way for us to better handle the initial error here, perhaps similarly to running `astro airflow deploy` without specifying a deployment name? Or the latter perhaps something like `no deployment specified` and the former something like `no deployment "dev" found`?

Deferring to you @schnie or @andriisoldatenko but figured I'd document in case that's something we want to change.

**Comment by schnie** [comment]
@paolaperaza in your second example, do you actually have deployments on the cloud or is it wrong about not having any airflow deployments?

**Comment by paolaperaza** [comment]
@schnie Yea should've clarified, but in this case I did not have _any_ deployments in that Workspace, so `No airflow deployments found` might be the right error there (and it's not just that one isn't specified since you'd otherwise be prompted to pick, but that none exist).

**Comment by schnie** [comment]
Cool, yep we can probably catch the `docker push` error and output a cleaner, more meaningful message there instead. I'll need @andriisoldatenko to verify that though.

**Comment by andriisoldatenko** [comment]
@schnie i think @sjmiller609 fix this issue ^
