### ISSUE TITLE
Feature Request: Ability to choose Executor when running `astro deployment create <deployment name>` via the CLI

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/astro-cli#248]
**Current State**

Running `astro deployment create <deployment name>` via the CLI defaults to the Celery Executor with default resources. A user cannot configure their new deployment's Airflow Executor directly and has to go to the Astronomer UI to modify.

If a user creates a Deployment via the UI, they're able to pick their Airflow Executor upon initial configuration (although the default selector sits on Celery by default).

**Ideal State**

For users creating deployments via the CLI, it'd be ideal to be able for them to be able to choose that deployment's executor directly in the CLI upon running `astro deployment create <deployment name>`, instead of having to change it if needed via the Astro UI after the fact.

**Customer Feedback**

Got two separate pieces of feedback on this just today:

> It would be nice to be able to set options within the cli deployment creation process so that I don’t have to turn to the gui to make those changes.

> When I create new Deployment by astro CLI, it will have default settings/resources. Can I set Executor of Deployment of my choice? Celery is the default Executor and I would set it as Local.

**Comment by schnie** [comment]
Agreed!

**Comment by andriisoldatenko** [comment]
@schnie @paolaperaza 
should it be extra parameter ? E.g. 
`astro deployment create --executor=celery <deployment name>`
or select box:

``` Please choose your executor (celery is default one)
1. local
2. celery
3. k8s

>
?

**Comment by andriisoldatenko** [comment]
```
➜  astro-cli git:(master) ✗ go run main.go deployment create --help
Create a new Astronomer Deployment

Usage:
  astro deployment create DEPLOYMENT [flags]

Aliases:
  create, cr

Flags:
  -e, --executor string   executor
  -h, --help              help for create
```

**Comment by schnie** [comment]
@andriisoldatenko awesome, I like the optional flag! Houston will default to celery for now if not specified. `KubernetesExecutor` after beta period.
