### ISSUE TITLE
Update to use new AuthConfig/AuthProvider schema

### ISSUE THREAD

**Issue by schnie** [astronomer/astro-cli#254]
We made some recent changes to the schema in Houston around AuthConfig. Looks like we need to upgrade the CLI to use it.

https://github.com/astronomer/houston-api/blob/master/src/schema.graphql#L52-L63

**Comment by schnie** [comment]
@andriisoldatenko looks like we have to update the code to look at the list of providers instead of the top-level `googleEnabled`, `githubEnabled` and `auth0Enabled` flags.

**Comment by andriisoldatenko** [comment]
cc @ashb
