### ISSUE TITLE
make docker client use older versions

### ISSUE THREAD

**Issue by andriisoldatenko** [astronomer/astro-cli#267]
https://github.com/docker/cli/blob/031d2f8e9660ca742c763d67e0fe8dae3533a361/cli/context/docker/load.go#L127-L133
cc @ashb @schnie

**Comment by ryw** [comment]
@andriisoldatenko is this a bug, feature, or cleanup?

**Comment by andriisoldatenko** [comment]
@ryw we can close it, cause it won't work with docker API version less than 1.38.
https://docs.docker.com/develop/sdk/
