### ISSUE TITLE
astro deploy not showing correct deployments

### ISSUE THREAD

**Issue by schnie** [astronomer/astro-cli#275]
Using the latest CLI on Datarouter, I switched my workspace to a different one, which works fine. I can `astro deployment list` and it shows the correct deployments. When I go `astro deploy`, it shows the list of deployments for a different workspace. It should show me the options for the workspace I switched to.

**Comment by ryw** [comment]
is this cli or API, related to #436

**Comment by schnie** [comment]
The other one was in orbit
