### ISSUE TITLE
astrocloud dev bash

### ISSUE THREAD

**Issue by kushalmalani** [astronomer/astro-cli#542]
- [x] I have checked that a similar [feature request](https://github.com/astronomer/astro-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**✍️ Is your feature request related to a problem? Please describe.**

Ability to bash into a airflow container

**🧩 Describe the solution you'd like**

Sometimes it's helpful to exec into the scheduler using something like `docker exec -it airflow_251fb0-scheduler-1 /bin/bash`

I do this often enough that I would benefit from a built-in command to do this, something like astrocloud dev bash.

**🤔 Describe alternatives you've considered**

**💡 Additional context**

**Comment by kushalmalani** [comment]
Original Issue - https://github.com/astronomer/cloud-cli/issues/51

**Comment by sunkickr** [comment]
the user should be able to bash into either webserver, scheduler, or postgres db with flags. The command should exec into the scheduler by default
