### ISSUE TITLE
Add Software team command to new CLI

### ISSUE THREAD

**Issue by kushalmalani** [astronomer/astro-cli#545]
- [x] I have checked that a similar [feature request](https://github.com/astronomer/astro-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**✍️ Is your feature request related to a problem? Please describe.**

The scope of this issue is to include all the team commands and underlying code logic from the older main of astro-cli to the new main branch

PRs to be migrated:
- https://github.com/astronomer/astro-cli/pull/518
- https://github.com/astronomer/astro-cli/pull/524
- https://github.com/astronomer/astro-cli/pull/526
- https://github.com/astronomer/astro-cli/pull/527

Issues which were pending in 0.x as well:
- https://github.com/astronomer/issues/issues/4311
- https://github.com/astronomer/issues/issues/4304
- https://github.com/astronomer/issues/issues/4303

**🧩 Describe the solution you'd like**

**🤔 Describe alternatives you've considered**

**💡 Additional context**

Original Ticket - https://github.com/astronomer/cloud-cli/issues/121

**Comment by sunkickr** [comment]
@neel-astro @kushalmalani is this done?

**Comment by neel-astro** [comment]
no, not yet, but this isn't a high priority at the moment, it will come up during the 0.30.0 software release cycle

**Comment by vishwas-astro** [comment]
@neel-astro please let me know if you have validated this change in some environment.

**Comment by neel-astro** [comment]
@vishwas-astro this has been validated against the QA environment

**Comment by neel-astro** [comment]
closing this one as this was just a ticket to complete the code migration from old CLI to new CLI, QA testing is being tracked on the original epic: https://github.com/astronomer/issues/issues/4301
