### ISSUE TITLE
astro dev pytest traverses all folders for test cases

### ISSUE THREAD

**Issue by kushalmalani** [astronomer/astro-cli#549]
- [x] I have checked that a similar [feature request](https://github.com/astronomer/astro-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**✍️ Is your feature request related to a problem? Please describe.**

The default behavior of pytest is to traverse all folders/files in the root directory to find test cases. This can cause issues if : customers are using words like "test" in python files, are bundling software in include with test cases, or building test harnesses for shared code across DAGs.

The default behavior of astro dev pytest should be to only search for test cases within the tests or tests/dags folder.

**🧩 Describe the solution you'd like**

**🤔 Describe alternatives you've considered**

**💡 Additional context**

Original ticket - https://github.com/astronomer/cloud-cli/issues/160

**Comment by sunkickr** [comment]
should be fixed now
