### ISSUE TITLE
Use Deployment API Key with Deployment Commands 

### ISSUE THREAD

**Issue by kushalmalani** [astronomer/astro-cli#553]
- [x] I have checked that a similar [feature request](https://github.com/astronomer/astro-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**✍️ Is your feature request related to a problem? Please describe.**

Productboard Feature: https://astronomer.productboard.com/feature-board/2193567-step-1-feature-backlog/features/13108784/detail

The deployment API key does not work with deployment commands for two reasons:

    The setup function only uses API keys with the deploy command
    Deployment commands use workspace permissions to validate a selected deployment id. This step can be skipped if a deployment id is specified

**🧩 Describe the solution you'd like**

**🤔 Describe alternatives you've considered**

**💡 Additional context**

**Comment by sunkickr** [comment]
I tried running all the deployment commands with deployment API keys and got the following results

insufficient user permissions(expected)
- astro deployment create

Worked with no issue(expected)
- astro deployment list
- astro deployment variable list

Worked but received error: "You must pass either an "anonymousId" or a "userId"." from the API(Not expected)
- astro deployment update
- astro deployment variable create
- astro deployment variable update

Worked but recived error: "Invalid deployment cl1xod1g0168051fzodxx232xe"(Not expected)
- astro deployment delete

**Comment by paolaperaza** [comment]
Notes from Sprint Planning - @kushalmalani Can you take a look at this to get a better idea of why these commands are failing? If straightforward, let's get it into this week's cycle with API core changes.

**Comment by kushalmalani** [comment]
The above linked PR fixes all the issues.

This wouldnt work with deployment create because you create a deployment level api key after the deployment is created. 

deployment create would work when workspace api keys will be introduced

CC: @paolaperaza @sunkickr
