### ISSUE TITLE
Tag dev releases for QA to automate

### ISSUE THREAD

**Issue by kushalmalani** [astronomer/astro-cli#560]
- [x] I have checked that a similar [feature request](https://github.com/astronomer/astro-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**✍️ Is your feature request related to a problem? Please describe.**

**🧩 Describe the solution you'd like**

Context: Currently we do not have a standard process to test pre-GA cli. As we have an automated CLI framework that runs on circleCI, we need an automated way to get the pre-released CLI bundles for all windows,mac and linux.

Something to get the latest dev cli

brew install astronomer/cloud/astro@dev
curl https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/@dev -o astro-cli.tar.gz

Ideally it would be nice to have the CLI follow something like this

https://app.circleci.com/pipelines/github/astronomer/astronomer/4056/workflows/0065efad-6db4-45b4-aba7-89d569331064

**🤔 Describe alternatives you've considered**

**💡 Additional context**

Original Ticket - https://github.com/astronomer/cloud-cli/issues/134

**Comment by neel-astro** [comment]
@kushalmalani just cleaning things up, is this issue still relevant since we no longer support astrocloud cli I assume, if so then maybe we can close the issue

**Comment by kushalmalani** [comment]
I think this still could be useful. It was created before the convergance, but something we can chat about to support for astro-cli in the next meeting.

**Comment by kushalmalani** [comment]
Discussed on Slack. Closing this.
