### ISSUE TITLE
Table select functions (workspace, cluster, deployment) could all be refactored into one TableSelect helper function to make maintainability more robust 

### ISSUE THREAD

**Issue by kushalmalani** [astronomer/astro-cli#561]
- [x] I have checked that a similar [feature request](https://github.com/astronomer/astro-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**✍️ Is your feature request related to a problem? Please describe.**

**🧩 Describe the solution you'd like**

Will most likely need Generics from Go 1.18 to make this work properly, just something to keep in mind!

i.e. if I'm doing a deployment selection I want to return a deployment, but if I'm doing a workspace selection I'll want to return a workspace. Additionally, the input list is going to have to its type parameterized as well.

**🤔 Describe alternatives you've considered**

**💡 Additional context**

**Comment by kushalmalani** [comment]
Original Ticket - https://github.com/astronomer/cloud-cli/issues/278

**Comment by wei-astronomer** [comment]
Closed as the implementation was done.
