### ISSUE TITLE
get values from astrohub API for scheduleraumin, scheduleraumax etc

### ISSUE THREAD

**Issue by kushalmalani** [astronomer/astro-cli#567]
https://github.com/astro-projects/astro-cli/blob/f5f8330289de0280c0596262f040bfbcff075ad0/cloud/deployment/deployment.go#L28-L36

**Comment by kushalmalani** [comment]
@frank-ye Was this addressed? If yes, Can you link the PR to the ticket

**Comment by frank-ye** [comment]
We're going to remove this configurability based on https://www.notion.so/astronomerio/Scheduler-Sizing-and-UX-in-Astro-b7ac9800b2a34b14bd1cf35253f8ee1b, should be addressed via: https://github.com/astronomer/astro/pull/2642

Thanks for the reminder :)

**Comment by kushalmalani** [comment]
I dont think we should close this yet, until we can validate there are no additional work required on the CLI. This ticket was primarily to pull the config from astrohub instead of hardcoding it in the CLI. Same thing we do with workerQueueOption, We need to build the same logic with deploymentConfigOptions.
