### ISSUE TITLE
astro deploy error on cloud - parse issue

### ISSUE THREAD

**Issue by kushalmalani** [astronomer/astro-cli#570]
It appears the dev parse is failing while being run during the deploy command. deploying with -f works fine

![Screen Shot 2022-05-18 at 3 29 19 PM](https://user-images.githubusercontent.com/63181127/169140839-aa1f417d-e637-40c7-9bd8-97c49a1e3295.png)

Original Ticket - https://github.com/astro-projects/astro-cli/issues/17

**Comment by sunkickr** [comment]
This has been fixed
