### ISSUE TITLE
Add podman support in astro CLI 1.0

### ISSUE THREAD

**Issue by neel-astro** [astronomer/astro-cli#573]
- [x] I have checked that a similar [feature request](https://github.com/astronomer/astro-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**✍️ Is your feature request related to a problem? Please describe.**
Add podman support for existing commands in astro-cli.
Astro CLI 0.x already had the feature, and having the feature in 1.x would help bring the new CLI in feature parity wrt existing CLI

Older PRs for reference:
- https://github.com/astronomer/astro-cli/pull/455
- https://github.com/astronomer/astro-cli/pull/461
- https://github.com/astronomer/astro-cli/pull/463
- https://github.com/astronomer/astro-cli/pull/514

Other older PRs, related to some way or other existing podman code: https://github.com/astronomer/astro-cli/pulls?q=is%3Apr+is%3Aclosed+podman

**🧩 Describe the solution you'd like**

**🤔 Describe alternatives you've considered**

**💡 Additional context**

**Comment by sunkickr** [comment]
@neel-astro is this planned work? or is this something we would need to plan to do?

**Comment by neel-astro** [comment]
we need to plan this

**Comment by stonecharioteer** [comment]
Is this something you folks are planning internally or would you be open to a PR for this?

**Comment by sunkickr** [comment]
@stonecharioteer we planning to do this eventually but if you wanted to create PR we would take that too

**Comment by neel-astro** [comment]
@stonecharioteer are you planning to raise a PR for this?

**Comment by sunkickr** [comment]
@rob-1126 has been working on this. I have been tracking the progress of podman support here: https://docs.google.com/spreadsheets/d/1S1JKb1gkgIeUzNz18u_sqXgynAv_Je5xoj-KbB1raKk/edit#gid=0
