### ISSUE TITLE
Make cloud.astronomer-dev.io(and stage) a vaild login domain

### ISSUE THREAD

**Issue by sunkickr** [astronomer/astro-cli#578]
- [X] I have checked that a similar [feature request](https://github.com/astronomer/astro-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Problem**

When an internal users runs `astro login cloud.astronomer-dev.io` or `astro login cloud.astronomer-stage.io` they will get a http error. This is because the cli doesn't translate these domains to their auth counterpart

**🧩 Describe the solution you'd like**

The CLI should take the domains  cloud.astronomer-dev.io and cloud.astronomer-stage.io as valid log in domains for Astro just like it does with cloud.astronomer.io

**🤔 Describe alternatives you've considered**

N/A

**💡 Additional context**

N/A

**Comment by kushalmalani** [comment]
Closing this since this has been addressed.
