### ISSUE TITLE
Fix local dev behaviour for runtime images in 0.29

### ISSUE THREAD

**Issue by neel-astro** [astronomer/astro-cli#582]
**Describe the bug**
Currently, when the local airflow setup is spun up with runtime images in 0.29, then the airflow components are trying to push task logs to s3 and failing with exceptions, in order to fix this, we would need to add env var `ASTRONOMER_ENVIRONMENT=local` in the docker-compose & pod-config files.

Exception:
```
[2022-06-01 01:44:56,490] {s3_task_handler.py:202} ERROR - Could not write logs to s3:///dag_id=scenario2_case3_001_01/run_id=scheduled__2022-05-27T03:00:00+00:00/task_id=tasks__60_of_100/attempt=1.log
 Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/airflow/providers/amazon/aws/log/s3_task_handler.py", line 191, in s3_write
     self.hook.load_string(
   File "/usr/local/lib/python3.9/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 63, in wrapper
     return func(*bound_args.args, **bound_args.kwargs)
   File "/usr/local/lib/python3.9/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 87, in wrapper
     bound_args.arguments['bucket_name'], bound_args.arguments[key_name] = S3Hook.parse_s3_url(
   File "/usr/local/lib/python3.9/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 142, in parse_s3_url
     raise AirflowException(f'Please provide a bucket_name instead of "{s3url}"')
 airflow.exceptions.AirflowException: Please provide a bucket_name instead of "s3:///dag_id=scenario2_case3_001_01/run_id=scheduled__2022-05-27T03:00:00+00:00/task_id=tasks__60_of_100/attempt=1.log"
```

**What CLI Version did you experience this bug?**
0.29.0

**What Operating System is the above CLI installed on?**

**🪜 Steps To Reproduce**

1. Init a local dev setup with runtime image using `astro dev init`
2. Spin up the airflow component using `astro dev start`
3. Make sure to turn on a DAG after the setup is up and running
4. Check the webserver logs, and observe the above mentioned exceptions traces

**📸 Screenshots**

**Comment by sunkickr** [comment]
@neel-astro can we close this issue?

**Comment by neel-astro** [comment]
The issue is just in 0.29.x release branch, the changes have been merged in `software-v0`, but I haven't created a patch release in 0.29 to fix it yet, will do it alongside 1.3.0. I am keeping this issue open until then.

**Comment by sunkickr** [comment]
@neel-astro has this been released yet?

**Comment by neel-astro** [comment]
will release it alongside 1.3.0

**Comment by Priyanka13Astro** [comment]
Verified on 0.29.2-rc2/0.29.1 pre-release cli version.

Verified as below:

1. Init a local dev setup with runtime image using astro dev init
2. Spin up the airflow component using astro dev start
3. Executed the DAG
4. Checked the webserver logs, and didn't observe the above mentioned exceptions traces.
5. Also checked Airflow Task logs are displayed on Airflow UI.
![Screenshot 2022-07-12 at 5.30.34 PM.png](https://images.zenhubusercontent.com/6262678e2423222c32492ee1/68c1c960-c734-4f3d-8142-359d62336cc3)
Attached the webserver Logs.[Uploading... webserver.log]
Working as expected so closing the issue.
