### ISSUE TITLE
Mismatch between UID when mounting volumes between systems

### ISSUE THREAD

**Issue by benjamingregory** [astronomer/astro-cli#59]
This isn't an issue for me currently because I found a workaround but wanted to capture this for posterity and a better long term solution. 

I was attempting to start our dockerized Airflow with mounted volumes on the following server:
```
$ cat /etc/*-release
CentOS Linux release 7.3.1611 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.3.1611 (Core) 
CentOS Linux release 7.3.1611 (Core) 
```

I ran into an issue where the default user we create  in the containers (`astro`) is not present on the home server and changing the user in the Dockerfile to my home user throws the following error: 
```
ERROR: for airflowenterprise_flower_1  Cannot start service flower: linux spec user: unable to find user ben.gregory: no matching entries in passwd file
Creating airflowenterprise_scheduler_1       ... 

ERROR: for airflowenterprise_scheduler_1  Cannot start service scheduler: linux spec user: unable to find user ben.gregory: no matching entries in passwd file

ERROR: for flower  Cannot start service flower: linux spec user: unable to find user ben.gregory: no matching entries in passwd file

ERROR: for scheduler  Cannot start service scheduler: linux spec user: unable to find user ben.gregory no matching entries in passwd file
ERROR: Encountered errors while bringing up the project.
```

To get around this, I attempted to add `RUN adduser -D -u 123456789876 -G astro ben.gregory` to the Dockerfile but ran into another issue.
```
$ docker build .
Sending build context to Docker daemon  3.072kB
Step 1/12 : FROM alpine:3.7
 ---> 3fd9065eaf02
Step 2/12 : RUN adduser -D -u 123456789876 -G astro ben.gregory
 ---> Running in 78bb924159c9
adduser: number 123456789876 is not in 0..256000 range
```

Some googling led me to this being an Alpine issue, specifically BusyBox which throws an error if the UID is greater than 256000 (https://stackoverflow.com/questions/41807026/cant-add-a-user-with-a-high-uid-in-docker-alpine?rq=1). It turns out Alpine doesn't actually care about the UID so I added the suggested workaround in the SO question. 
```
# Create user
echo "ben-gregory:x:$UID_TO_SET:$UID_TO_SET::/home/ben-gregory:" >> /etc/passwd
## thanks for http://stackoverflow.com/a/1094354/535203 to compute the creation date
echo "ben-gregory:!:$(($(date +%s) / 60 / 60 / 24)):0:99999:7:::" >> /etc/shadow
echo "ben-gregory:x:$UID_TO_SET:" >> /etc/group
mkdir /home/ben-gregory && chown user: /home/ben-gregory
```
FWIW, BusyBox also won't let you add a user with a period so ben.gregory had to become ben-gregory, but it could as easily have been left as `user`.

Finally I had to change the Dockerfile for airflow to `chown` the directory to my new user from `astro`.

**Comment by schnie** [comment]
@andscoop he was using the open edition docker-compose example but this is also an issue for the cli.

**Comment by andscoop** [comment]
@benjamingregory Do you have any logs around the original error?
>I ran into an issue where the default user we create in the containers (astro) is not present on the home server
