### ISSUE TITLE
`astro deployment variable create` command truncates long ENV Vars when sending to deployment

### ISSUE THREAD

**Issue by aspain** [astronomer/astro-cli#590]
**Describe the bug**

When a customer used the `astro deployment variable create --deployment-id <deployment-id> --load --env .env` command, it was truncating a long ENV Var value when sending to the Astro UI

When the customer instead manually copy/pasted the full Env VAR into the Astro UI, it saved the entire ENV Var value

Is there a character limit for the CLI for loading env vars? This was a secrets backend variable for GCP which includes a long keyfile json character string

**What CLI Version did you experience this bug?** 
Customer was using astrocloud, unsure if this is an issue with new `astro` CLI?

**What Operating System is the above CLI installed on?**

Windows

**Comment by sunkickr** [comment]
do you have a rough idea on how many characters it was? I cannot seem to find a limit on mac so maybe it is only an issue on windows

**Comment by aspain** [comment]
@sunkickr it included a full google keyfile json, looking at one I have on hand it is over 2,300 characters just for the json file, in addition to the other settings in the ENV Var

**Comment by aspain** [comment]
From the customer:

```
When we first flagged that problem, I was running the command in Ubuntu 20.04.2 LTS in WSL 2 on Microsoft Windows 10 Home version 10.0.19044
Currently I have Astro CLI Version: 1.0.2... I do not think I upgraded since then
```

**Comment by sunkickr** [comment]
I'll try testing on ubuntu

**Comment by sunkickr** [comment]
I tired this on ubuntu with a 6000 character evn var and it worked as expected

**Comment by sunkickr** [comment]
It is probably a WSL issue

**Comment by sunkickr** [comment]
will need to test on wsl

**Comment by nkapinos** [comment]
@sunkickr  is this still open?

**Comment by nkapinos** [comment]
@sunkickr @paolaperaza can you make sure this one is in correct status?  still showing as 'in-progress'

**Comment by sunkickr** [comment]
yes this is still open

**Comment by sunkickr** [comment]
I think I have finally figured out what is causing this issue. The CLI will cut a value short if it contains a "=" character
