### ISSUE TITLE
Error when Authenticating to Astronomer Software

### ISSUE THREAD

**Issue by ReadytoRocc** [astronomer/astro-cli#597]
**Describe the bug**
When I run `astro login BASE_DOMAIN` to authenticate to an Astronomer Software instance (v0.28.4), I receive the following error:

```
Failed to authenticate to the registry. Do you have Docker running?
You will not be able to push new images to your Airflow Deployment unless Docker is running.
If Docker is running and you are seeing this message, the registry is down or cannot be reached.
```

**What CLI Version did you experience this bug?**
Astro CLI Version: 1.0.1

**What Operating System is the above CLI installed on?**
macOS 12.3.1

**Comment by neel-astro** [comment]
Closing this because I am not able to replicate the issue. Feel free to reopen if the issue persists @ReadytoRocc, but based on the error message most likely it is just because of docker not running during `astro login`
