### ISSUE TITLE
SPIKE: Investigate impact on Astro CLI for new Worker Queues Input instead of DeploymentSpec.workers.au

### ISSUE THREAD

**Issue by frank-ye** [astronomer/astro-cli#599]
Once worker queue infra work gets deployed, we'll deprecate the AU slider in the Cloud UI, and ask users to input Worker Queue parameters instead. The ticket is meant to track the changes on the CLI required to support this schema / input pattern change. 

Sample input can be found in the description here: https://github.com/astronomer/astro/pull/831

One thing to note is that the `isDefault` field is going to be enforced in the GraphQL input, and that the `update` WorkerQueues field in the `deploymentUpdate` mutation will require the final state of all worker queues, i.e. inputs with no ID are considered new queues, inputs with IDs are mods on existing queues, and the absence of a queue --> deletion.

**Comment by sunkickr** [comment]
Worker queues input impact on the CLI is outlined here: https://www.notion.so/astronomerio/Worker-Queue-CLI-Commands-ae1238842d4c43f49793c4c1313aae1e
