### ISSUE TITLE
Check version mismatch between target and build when calling `astro deploy`

### ISSUE THREAD

**Issue by cdabella** [astronomer/astro-cli#616]
- [x] I have checked that a similar [feature request](https://github.com/astronomer/astro-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**✍️ Is your feature request related to a problem? Please describe.**

The build step of `astro deploy` is often the bulk of the deploy process (on the order of minutes), but if I'm not careful the end result will be a failure because version is incompatible with the target Airflow deployment. This can cause unexpected delays during both development and failures within CICD

**🧩 Describe the solution you'd like**

Before the build step, the astro CLI can check the target Airflow version and the base image to make sure that the versions are aligned. This would have an added benefit of checking if the deploy was going to start an upgrade or even if the base image itself was not built from an astro image.

**🤔 Describe alternatives you've considered**

Docker has the `history` command which shows all Dockerfile commands used in the creation of an image. If run against a base image, the CLI could check for the environment variables being set to identify and verify the astro version without building the image itself. 

```
$ docker history el_901e15/airflow
IMAGE          CREATED        CREATED BY                                      SIZE      COMMENT
[snip]
<missing>      9 days ago     ENV DEBIAN_FRONTEND=noninteractive PIP_NO_CA…   0B        buildkit.dockerfile.v0
<missing>      9 days ago     ENV PYTHONPATH=/usr/local/airflow               0B        buildkit.dockerfile.v0
<missing>      9 days ago     ENV AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER…   0B        buildkit.dockerfile.v0
<missing>      9 days ago     ENV ASTRONOMER_RUNTIME_VERSION=5.0.4            0B        buildkit.dockerfile.v0
<missing>      9 days ago     ENV ASTRONOMER_ENVIRONMENT=cloud                0B        buildkit.dockerfile.v0
<missing>      9 days ago     ENV ASTRONOMER_UID=50000                        0B        buildkit.dockerfile.v0
<missing>      9 days ago     ENV ASTRONOMER_USER=astro                       0B        buildkit.dockerfile.v0
<missing>      9 days ago     ENV AIRFLOW_HOME=/usr/local/airflow             0B        buildkit.dockerfile.v0
<missing>      9 days ago     ARG ORG=astronomer                              0B        buildkit.dockerfile.v0
[snip]
```

**💡 Additional context**

I'm not sure what edge cases might be present in how the CLI is used today, and how robust using the history is for long-term use.

**Comment by neel-astro** [comment]
We can maybe simply inspect the image for the airflow or runtime version label, that might be more reliable. Also, is this related to just trying to deploy to Astro via `astro deploy`?, because I believe on Software `astro deploy` will throw a warning if there is a version mismatch.

**Comment by neel-astro** [comment]
Closing this as the check already exists for `astro deploy` on the Software platform. Feel free to reopen if there is any shortcoming in the current approach or if it's not related to the Software
