### ISSUE TITLE
Upgrade CLI to go 1.18

### ISSUE THREAD

**Issue by kushalmalani** [astronomer/astro-cli#617]
- [x] I have checked that a similar [feature request](https://github.com/astronomer/astro-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**✍️ Is your feature request related to a problem? Please describe.**

Upgrade CLI to go version 1.18

**🧩 Describe the solution you'd like**

**🤔 Describe alternatives you've considered**

**💡 Additional context**

**Comment by sunkickr** [comment]
@kushalmalani should we close this ticket?

**Comment by kushalmalani** [comment]
We can, since its merged to main
