### ISSUE TITLE
Multi arch runtime image support for local dev

### ISSUE THREAD

**Issue by neel-astro** [astronomer/astro-cli#638]
- [x] I have checked that a similar [feature request](https://github.com/astronomer/astro-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**✍️ Is your feature request related to a problem? Please describe.**

Runtime team is bringing in new multi-arch images, which will allow docker to not need to emulate on ARM machines since new images would be built for both ARM & AMD64. This will enable a faster start-up time for the users during `astro dev start`. Attaching timings with a new image on M1 mac, timing improved to 34sec as compared to the usual 3-5 minutes:

<img width="1273" alt="Screenshot 2022-07-06 at 11 30 14 PM" src="https://user-images.githubusercontent.com/92356010/177614063-8b2be7f8-c056-4b3b-9d20-06eedca678db.png">

Related runtime PR: https://github.com/astronomer/astro-runtime/pull/306 

**🧩 Describe the solution you'd like**

- `astro dev` commands should be compatible with the new image, and might not require any changes
- `astro deploy` for both cloud & software should ensure they cross-compile to AMD64 on ARM-based machines while building & pushing the image to registry

**🤔 Describe alternatives you've considered**

**💡 Additional context**

**Comment by ianbuss** [comment]
Have updated the astro-runtime PR to fix the testing on ARM64. So we should be very close to ready (approvals pending) to pull the trigger when safe to do so.

**Comment by neel-astro** [comment]
To be tested against multi-arch supported runtime image (`quay.io/astronomer/astro-runtime-dev:055d4c9a76b327a78f6c4abcc9ed582fa6d6ffff`)

**Comment by Priyanka13Astro** [comment]
Verified with CLI 1.4.0 & m1 Mac
1. Verified that `astro dev` commands work as expected with the new image mentioned above.
2. Verified that `astro deploy` command also works as expected with the new image mentioned above.

![Screenshot 2022-08-10 at 10.38.26 PM.png](https://images.zenhubusercontent.com/6262678e2423222c32492ee1/33d630a4-bdb7-4f94-bcf1-6307e5c7d1cb)

![Screenshot 2022-08-10 at 10.47.43 PM.png](https://images.zenhubusercontent.com/6262678e2423222c32492ee1/a8207736-6b77-48c9-b771-b442023f9ece)

![Screenshot 2022-08-10 at 10.47.16 PM.png](https://images.zenhubusercontent.com/6262678e2423222c32492ee1/085034f3-3c54-4ba2-9341-69711dafd9c4)
