### ISSUE TITLE
Move all Private API calls to Public API calls for PR-RBAC

### ISSUE THREAD

**Issue by sunkickr** [astronomer/astro-cli#642]
- [X] I have checked that a similar [feature request](https://github.com/astronomer/astro-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**✍️ Is your feature request related to a problem? Please describe.**

The new Workspace RBAC model does not work with the private API.

**🧩 Describe the solution you'd like**

All private API call made the CLI will need to changed to public API calls 
1. Find all Private API calls used by the Astro CLI
2. Change them to public API calls that achieve the same thing 

**🤔 Describe alternatives you've considered**

**💡 Additional context**

**Comment by paolaperaza** [comment]
Note from standup: Not super urgent as we currently believe that APIs are backwards compatible, but @kushalmalani will still work on this. Next steps is figure out deprecation of `astrocloud` and `astro` 1.0-1.3.

**Comment by kushalmalani** [comment]
Blocked on: https://github.com/astronomer/astro/issues/3174

**Comment by wei-astronomer** [comment]
@kushalmalani Create a ticket to migrate old API keys.
