### ISSUE TITLE
Deprecate Astro CLI v1.0.0-1.3.0 for Cloud Users for New RBAC Model

### ISSUE THREAD

**Issue by sunkickr** [astronomer/astro-cli#646]
- [X] I have checked that a similar [feature request](https://github.com/astronomer/astro-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**✍️ Is your feature request related to a problem? Please describe.**

We will need to deprecate early versions of the Astro CLI v1 to move all users over to the new RBAC model

**Comment by kushalmalani** [comment]
@sunkickr What do we need to do here?

**Comment by sunkickr** [comment]
nothing just `Astro CLI v1.0.0-1.3.0` is not supported
