### ISSUE TITLE
List Virtual Runtimes in Astro CLI

### ISSUE THREAD

**Issue by chuangliuastronomer** [astronomer/astro-cli#650]
## Description

Based on discussions, we need a way to list all virtual run times in CLI. It means CLI needs to talk to core-api to fetch a list of virtual run times. The Particular UI of the VR listing is TBD by product

**Comment by paolaperaza** [comment]
Removing this from scope for alpha -- plan is to have users run `astro deploy <virtual-runtime-id> -- dags` and AstroHub to understand difference between VR + Deployment ID

Still has to get done, but not for alpha

**Comment by kushalmalani** [comment]
Closing this ticket since we not longer support this product
