### ISSUE TITLE
Use `semver.NewVersion` instead of `semver.MustParse` 

### ISSUE THREAD

**Issue by neel-astro** [astronomer/astro-cli#657]
**Describe the bug**
We are currently using the `semver.MustParse` method to parse versions in CLI. This would cause an issue when either an invalid version string is passed in some form from the user end or the version present in the image itself is invalid, in both cases `semver.MustParse` will cause panic in code execution. 

Ideally, we should avoid panic in our Go code, and so the idea is to use `semver.NewVersion` instead of `semver.MustParse` wherever we are getting the version string from the user's end, this would avoid code panics and give us errors which can be handled inside our code. Also if possible we should have a fallback in case of an error.

Ex:
Current Code in `docker.go` `Start` method 
```Golang
if version := semver.MustParse(airflowVersion); version != nil {
    airflowDockerVersion = version.Major()
}
```

Expectation:
```Golang
version, err := semver.NewVersion(airflowVersion)
if err != nil {
	airflowDockerVersion = 2 // fallback assuming it's Airflow 2, in order to handle the error
} else {
	airflowDockerVersion = version.Major()
}
```
**What CLI Version did you experience this bug?**

**What Operating System is the above CLI installed on?**

**🪜 Steps To Reproduce**

1. In your local project's Dockerfile add an airflow version label with an invalid semver, ex: `LABEL io.astronomer.docker.airflow.version="2.4.0.dev20220719"`
2. try `astro dev start`
3. observer the panic in the code wrt semver library not being able to parse the image version

**📸 Screenshots**

**Comment by neel-astro** [comment]
steps to test:
- In your local project's Dockerfile add an airflow version label with an invalid semver, ex: `LABEL io.astronomer.docker.airflow.version="2.4.0.dev20220719"`
- run `astro dev start`
- `astro dev start` should work fine without any code panic

**Comment by himabindu07** [comment]
Validated On: Astro CLI 1.6.0 
Dockerfile: 
`FROM quay.io/astronomer/ap-airflow-dev:2.4.0.dev20220719`
ran:  `astro dev start`
<img width="1023" alt="Screen Shot 2022-09-21 at 3 26 40 PM" src="https://user-images.githubusercontent.com/47584863/191621330-6ef87f98-7f1d-4ef0-b06e-9098fb73b4b1.png">

```
Airflow is starting up! This might take a few minutes…
unable to parse airflow version, defaulting to major version 2, error: Invalid Semantic Version
```
@neel-astro  seeing the above error Is that expected?

**Comment by neel-astro** [comment]
yes, that is expected
