### ISSUE TITLE
Move python code into separate files

### ISSUE THREAD

**Issue by neel-astro** [astronomer/astro-cli#664]
- [x] I have checked that a similar [feature request](https://github.com/astronomer/astro-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**✍️ Is your feature request related to a problem? Please describe.**
The idea is to maintain python code in a separate python file instead of the current way of maintaining it as a static Golang string

Current files:
- https://github.com/astronomer/astro-cli/blob/main/airflow/include/dagintegritytest.go
- https://github.com/astronomer/astro-cli/blob/main/airflow/include/dagintegritytestdefault.go
- https://github.com/astronomer/astro-cli/blob/main/airflow/include/advancedexampledag.go
- https://github.com/astronomer/astro-cli/blob/main/airflow/include/basicexampledag.go

This will allow us to maintain that logic as python code and apply python linting and black

**Comment by nitinmewar** [comment]
can I work on it?
