### ISSUE TITLE
 UX improvement for teams list/get commands

### ISSUE THREAD

**Issue by neel-astro** [astronomer/astro-cli#681]
- [x] I have checked that a similar [feature request](https://github.com/astronomer/astro-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**✍️ Is your feature request related to a problem? Please describe.**
The current Teams get/list CLI command has a couple of shortcomings:
- There is no way to get the system-level roles for team/s
- The output of `astro deployment team list` and `astro workspace team list` list all the roles for that team irrespective of the resource/entity type it was called from i.e. `astro workspace team list` should ideally return back workspace level roles only. Currently, it would also return deployment & system-level roles.
Ex:
<img width="753" alt="Screenshot 2022-08-09 at 12 21 06 PM" src="https://user-images.githubusercontent.com/92356010/183679619-acbcf7e1-078d-4c8f-8390-b28279b2b82f.png">

**🧩 Describe the solution you'd like**
- `astro team list` command should display system-level roles
- `astro team get` command should display both system level role as well as individual resource level roles, i.e. for a given team list  roles for all the defined workspace and deployments.
- `astro deployment team list` should display deployment level roles for that deployment
- `astro workspace team list` should display workspace level roles for that workspace

**💡 Additional context**

Reference to the slack discussion: https://astronomer.slack.com/archives/C03JM4MV8LF/p1660025341388039

**Comment by Priyanka13Astro** [comment]
Verified on 1.5.0/ qa (0.30.0)
The test cases covered for this fix are here https://www.notion.so/astronomerio/1036f9b98a9e4d5daec545f0c45feaaf?v=5264c656fa914661809a748f0612b852
Working as expected so closing this issue.

**Comment by neel-astro** [comment]
closing this, as has been verified by QA
