### ISSUE TITLE
astro deploy gives error about name while it expects id instead

### ISSUE THREAD

**Issue by BasPH** [astronomer/astro-cli#691]
A customer running Astro CLI 1.1 and Astro Software 0.28.4 received this error running `astro deploy [deployment-name]` (using a valid deployment name):

```
please specify a valid deployment name
```

However, the CLI expects the deployment id, so the error message is misleading.

Error message in code: https://github.com/astronomer/astro-cli/blob/e24b6547e61eaf506010d7a35394b98a5ed540d9/software/deploy/deploy.go#L33

**What CLI Version did you experience this bug?**

1.1

**Comment by neel-astro** [comment]
This has been added to the `1.5.0` pre-release
