### ISSUE TITLE
Add a `--no-browser` flag to `astro dev start`

### ISSUE THREAD

**Issue by BasPH** [astronomer/astro-cli#693]
User is running `astro dev start` on a w3m terminal, which leaves them stuck in a login page:

![Astro CLI webpage](https://user-images.githubusercontent.com/6249654/185605885-cf495b88-f6ae-4e3e-8542-3d5256904b5b.png)

Astro CLI 1.4.0, w3m terminal.

It would be convenient to have e.g. a `--no-browser` flag to disable this behaviour, or somehow detect if a screen is attached.

**Describe the bug**

```
Please paste terminal or playground output in a code block here
```

**What CLI Version did you experience this bug?**

**What Operating System is the above CLI installed on?**

**🪜 Steps To Reproduce**

**📸 Screenshots**

**Comment by neerajvash8** [comment]
Ideally default value should be set to false, it is an added feature to the astro cli (command line interface) not a default behaviour. 
User should have the cli to work on the terminal. 

w3m is a terminal [browser](http://w3m.sourceforge.net/)

**Comment by BasPH** [comment]
@neerajvash8 I'm afraid you're one of the few that runs `astro dev start` from a terminal without screen. I think it's desirable for almost all users to open the browser by default.

Jupyter has the same behaviour: running `jupyter notebook` will open your browser by default, and it can be disabled by setting a flag `jupyter notebook --no-browser` ([docs](https://docs.jupyter.org/en/latest/running.html#how-do-i-start-the-notebook-server-without-opening-a-browser)).

**Comment by sunkickr** [comment]
I agree it looks like a --no-browser flag is needed
