### ISSUE TITLE
`astro airflow start` and `astro airflow stop`

### ISSUE THREAD

**Issue by ryw** [astronomer/astro-cli#7]
clean up libcompose logging + log out URLs

**Comment by andscoop** [comment]
@schnie Are we planning on doing a fork of libcompose to handle this still?

**Comment by schnie** [comment]
Yea, we may have to. There's an issue that hasn't had much action: https://github.com/docker/libcompose/issues/487

**Comment by andscoop** [comment]
Getting closer on this one - dug in a bit this morning, findings can be reviewed on the linked issue above.

Summary - we have a way to suppress the majority of the logs with a simple mod to our vendored libcompose package. Overall, it is still not clear why libcompose does not respect log level.
