### ISSUE TITLE
Refactor deployment.Update

### ISSUE THREAD

**Issue by sunkickr** [astronomer/astro-cli#705]
- [X] I have checked that a similar [feature request](https://github.com/astronomer/astro-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**✍️ Is your feature request related to a problem? Please describe.**

`worker-queue create` is using the `deployment.Update` function which is causing `worker-queue create` to print a table and an extra deployment ID as shown in the screen shot below:
<img alt="image" width="1405" src="https://user-images.githubusercontent.com/63181127/187252205-7af82628-ccdc-4870-bdaf-c5ba25b5cf72.png">

**🧩 Describe the solution you'd like**

- The extra deployment ID is a mistake and the print statement should be removed
- deployment.Update function should be refactored so that the deployment table comes up when the `deployment update` command is run but not the `deployment worker-queue create` command

**🤔 Describe alternatives you've considered**

**💡 Additional context**

**Comment by jemishp** [comment]
The extra deploymentID is being printed from [this line](https://github.com/astronomer/astro-cli/blob/main/cloud/deployment/deployment.go#L641) 

The table print out is coming from `deployment.Update()` [here](https://github.com/astronomer/astro-cli/blob/main/cloud/deployment/deployment.go#L498..L500) 

We may handle it in #639 when we deprecate `worker-AU` as we will be changing deployment but its good to track separately.
