### ISSUE TITLE
Add warning about how docker images are named

### ISSUE THREAD

**Issue by vparekh94** [astronomer/astro-cli#73]
Each image right now is named for the repository it is in. If a user has a project structure like this:

p1 -> airflow -> prod -> _astro_directory_

p2 -> airflow -> prod -> _astro_directory_

Running `astro airflow start` in p1's project, `astro airflow stop` and then running `astro airflow start` in p2's astro directory would spin up the same image as what's in p1. 

This could cause issues for users with multiple airflow deployments in multiple projects

**Comment by andscoop** [comment]
I can provide some warnings around this after #96 is in place

**Comment by andscoop** [comment]
I have a fix for this - but it would result in some customers having to rename docker images. 

@vparekh94 Going to un-assign myself for now, let me know when you want to revisit.

https://github.com/astronomerio/astro-cli/tree/feature/73-guarantee-unique-project-names

**Comment by schnie** [comment]
@andscoop should we merge this in and close it out? If we don't want to do this then we can just close it out. Seems like a reasonable fix to me. Would this actually have any impact on customers? Seems like when they start back up locally that it'd just retag it and run it seamlessly.
