### ISSUE TITLE
astro deployment create --deployment-file

### ISSUE THREAD

**Issue by sunkickr** [astronomer/astro-cli#733]
- [X] I have checked that a similar [feature request](https://github.com/astronomer/astro-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

https://www.notion.so/astronomerio/Deployments-as-Code-9024adfb689d469ab6ad549bbd325870?d=0f107684fecb48a5a17731090a50625f#61b88ed79a5640e081c50acdcfb08219

**Comment by jemishp** [comment]
Spoke with @sunkickr on progress to date. We are making the following changes:

- add all the Ids to `metadata` section so users can query that section for the id
- add names to `configuration` section so users can use names to create deployment
- add `dag_deploy_enabled` to `configuration` section

Once we get to that point we can PR and ship this feature.
