### ISSUE TITLE
CLI PR preview domains support

### ISSUE THREAD

**Issue by jcom000** [astronomer/astro-cli#744]
This ticket blocks deployment tests on pr preview.

```
➜  astro git:(pr-preview-cli) ✗ astro login pr4061.cloud.astronomer-dev.io
Error: Error! Invalid domain. You are attempting to login into Astro. Are you trying to authenticate to Astronomer Software? If so, please change your current context with 'astro context switch'
```

Supporting PR previews with the CLI is a huge endeavor. Every critical code path with hardcoded values like these would need to change.
```
	deploymentURL := "cloud." + c.Domain + "/" + workspaceID + "/deployments/" + d.ID + "/analytics"
```
talking with @kushalmalani and @jemishp, we think the best solution would be to write a helper utility to refactor all hardcoded urls.

we'll literally be scanning the code for each time the words "domain" or "localhost" etc. are used. Not all of these instances are relevant, but they're used about 500 times, and we'll have to scan through nonetheless.

**Comment by jemishp** [comment]
High level plan to discuss with the CLI team:
1. Make `getDeploymentURL()` helper that takes a `deploymentID`, `workspaceID` as parameters and returns a `deploymentURL` after getting the domain from the current context.
2. `inspect.go` uses `getDeplpymentURL()` helper
3. `deployment.go` needs to use the getDeploymentURL()` helper
4. `deploy.go` needs to use the getDeploymentURL()` helper 
5. `auth.go` has a `ValidateDomain()` that uses a list to validate domain against. Make that use the `context.IsCloudDomain()` instead
6. Modify `context.CloudDomainRegex` to allow pr preview environments or inject the correct URLs into `~/.astro/config.yaml` for PR preview envs.

Note: `Houston.DeploymentURL` is used by `software.deploy.go` and `software.deplyment.go`. Need to read more code to see if cloud changes would have any impact there.
