### ISSUE TITLE
Errors & behavior of object export flags

### ISSUE THREAD

**Issue by aspain** [astronomer/astro-cli#768]
**Describe the bug**

1. some connections are export with errors around parsing port number, such as:

```
Issue with parsing port number: strconv.Atoi: parsing "": invalid syntaxExporting Connection: google_cloud_default
Issue with parsing port number: strconv.Atoi: parsing "": invalid syntaxExporting Connection: snowflake_test
```

2. when using the `-s, --setings-file` flag, the help menu mentions it can be a settings file *or* an env file, however when I try specifying a `.env`, for example `testtry2.env`, it gives this error (note that I specivied a `.env` file type and the error mentions `.yaml`):

```
Error reading config in home dir: open /Users/aspain/git/cs-tutorial-repos/cs-tutorial-adam-dev/testtry2.yaml: no such file or directory
```

And then it instead creates a `testtry2.yaml` file to place the output in the project directory 

**Full output from the two issues mentioned above:**
```
aspain@astro ~/git/cs-tutorial-repos/cs-tutorial-adam-dev % astro dev object export -c -s testtry2.env 
Error reading config in home dir: open /Users/aspain/git/cs-tutorial-repos/cs-tutorial-adam-dev/testtry2.yaml: no such file or directory
Issue with parsing port number: strconv.Atoi: parsing "": invalid syntaxExporting Connection: google_cloud_default
Issue with parsing port number: strconv.Atoi: parsing "": invalid syntaxExporting Connection: snowflake_test
Exporting Connection: cli-conn-export-test
successfully exported Connections


Airflow objects exported to settings file
```

**What CLI Version did you experience this bug?**
1.6.0

**What Operating System is the above CLI installed on?**
MacOS 12.6

**🪜 Steps To Reproduce**
1. Have a few connections set up in Airflow UI
2. execute command: `astro dev object export -c -s testtry2.env`

**📸 Screenshots**
For the two errors around parsing the port, this is how the connections are set up in the Airflow UI:

Snowflake:
![image](https://user-images.githubusercontent.com/15913202/192859134-c91af57e-82bc-4971-8c28-e7b1565dd421.png)

Google Cloud (note this one doesn't even have a `port` parameter):
![image](https://user-images.githubusercontent.com/15913202/192859169-5ba18868-4bb0-4f69-99c7-5c7036337bc4.png)

**Comment by aspain** [comment]
Good chance I may be using this new command improperly, but the help menu makes it seem like you can specify a `.env` file when using the `-c -s` flags, but it appears it requires a `.yaml` instead

**Comment by sunkickr** [comment]
PR associated with this was merged
