### ISSUE TITLE
1.6.0 windows artifacts aren't archived/zipped.

### ISSUE THREAD

**Issue by andrewrothstein** [astronomer/astro-cli#770]
Is that intentional? Would be most useful for ppl trying to install the cli to have it be consistently packaged, i.e. either archived executables or bare executables, and not both depending on the target operating system.

**Comment by neel-astro** [comment]
The idea is to get away from having users run a multi-step install process for astro-cli on Windows and to have package manager support in the longer run. Unfortunately, in order to provide package manager support, we had to move from archived executables to bare executables.

**Comment by andrewrothstein** [comment]
none of this is unfortunate so long as it's intentional. when will u me be migrating to bare executables for the linux release artifacts? good for the goose; good for the gander, innit?

**Comment by neel-astro** [comment]
Not a high priority at the moment, since we expect users to directly use the curl command: https://github.com/astronomer/astro-cli#linux to install the required CLI version.
