### ISSUE TITLE
Unable to dag deploy some file type of `Alias` with Dag based deployment

### ISSUE THREAD

**Issue by dsgupta02** [astronomer/astro-cli#791]
**Describe the bug**

Unable to deploy some dags file kind `Alias` 

**🪜 Steps To Reproduce**

Tried to deploy DAGs from [scheduler_ha_benchmarking](https://github.com/astronomer/qa-scenario-dags/tree/master/scheduler_ha_benchmarking) branch of the  [qa-scenario-dags](https://github.com/astronomer/qa-scenario-dags) into [dag-perf-test2](https://cloud.astronomer-dev.io/cl0cpgejc48581fy1je3pqv07/deployments/cl8yhid2f1024762zy9iful3el1/analytics) deployment

1. Created deployment and deploy dag using binary (DAG downloader ON)
2. Did `astro deploy --dags` to deploy this [folder](https://github.com/astronomer/qa-scenario-dags/tree/master/scheduler_ha_benchmarking/scenario1/case2) which has 10 dag files init. Got below error msg
        `Error: archive/tar: write too long`
4. Could only able to deploy first file successfully.  (Removed remaining 9 files).
5. Did `astro deploy` with given binary getting same error.  
       `Error: archive/tar: write too long`
6. Tried astro deploy to deploy using CLI version 1.5.0 (DAG downloader OFF). It shows below message
      `Successfully pushed Docker image to Astronomer registry. Navigate to the Astronomer UI for confirmation that your deploy was successful.`
    - But in Airflow UI all the existing dags are removed i can see only monitoring dag. (Screenshot is in thread)
9. The File which not getting deployed are kind is `Alias` not Python (Screenshot below)

Note: 

- Can deploy same kind _(Alias)_ of file in with older version with new project initialisation and new deployment.
[Deployment - test_old_deploy](https://cloud.astronomer-dev.io/cl0cpgejc48581fy1je3pqv07/deployments/cl8ym0ryw1809471ivmh0233cvl/analytics)

- Can able to deploy in the [dag-perf-test2](https://astronomer.astronomer-dev.run/d0233cvl/home) deployment with older version and new project initialisation

**What CLI Version did you experience this bug?**
Astro CLI Version: SNAPSHOT-1df11733

**📸 Screenshots**

<img width="1480" alt="Screenshot 2022-10-07 at 7 49 36 PM" src="https://user-images.githubusercontent.com/100349882/194622667-ba41deac-0063-4a81-89f2-7fce21aabeb9.png">

<img width="721" alt="Screenshot 2022-10-07 at 7 29 14 PM" src="https://user-images.githubusercontent.com/100349882/194622682-44e64f6f-1caa-4da0-b2b9-1e8e29721759.png">

**Comment by kushalmalani** [comment]
Backend Fix for the same - https://github.com/astronomer/astro/issues/4946
