### ISSUE TITLE
Unable to deploy DAG files with large number of dags and tasks.

### ISSUE THREAD

**Issue by dsgupta02** [astronomer/astro-cli#809]
**Describe the bug**

Did some performance test around deploying a large dag file and share the test observation in [DAG Deployment Test Plan](https://www.notion.so/astronomerio/DAG-Deployment-Test-Plan-WIP-623b4aa08ef54667aabb44aa1c96519e)
Please look for test case named as

- Large Number of DAGs
- DAG file with large size
- DAGs with large number of tasks

Using [example_dag_generator.py](https://github.com/astronomer/qa-scenario-dags/tree/master/scripts/example_dag_generator) script to create dag file.

Note:   When i cross checked with old deploy approach we can see same behaviour (not working)
**_What worked in both old and new approach is deploying Dag 100 with 100 tasks_**

For `100 DAGs x 1000 Tasks` and `1000 DAGs x 100 Tasks`

- New approach getting below error in UI (as not getting parse, for parse we need to add --pytest/--parse flag ) and old approach getting same error in CLI as it is getting parsed.

```
Broken DAG: [/usr/local/airflow/dags/dags-from-volume-mount/dags/example_dag_1(1000x100).py] Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/dag.py", line 681, in __hash__
    return hash(tuple(hash_components))
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /usr/local/airflow/dags/dags-from-volume-mount/dags/example_dag_1(1000x100).py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow/latest/best-practices.html#top-level-python-code
* http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow/latest/best-practices.html#reducing-dag-complexity, PID: 2532
```

<img width="1499" alt="Screenshot 2022-10-12 at 10 53 54 PM" src="https://user-images.githubusercontent.com/100349882/195411491-6bd85f4d-56ed-4b9e-b4ec-a366450c58d4.png">
<img width="1231" alt="Screenshot 2022-10-12 at 10 53 37 PM" src="https://user-images.githubusercontent.com/100349882/195411502-cc80f7bb-53df-456a-8668-bf3a72034f8b.png">

Noticed one wired thing with new dag deploy approach is

1. created new [deployment](https://cloud.astronomer-dev.io/cl0cpgejc48581fy1je3pqv07/deployments/cl95m11jl1357222dzp2q7nuf7k/analytics)
2. Did astro deploy  (a dag file with 100 dags x 10000 of tasks)
3. Got this error
```
Attaching to 1e9da1-test-1
1e9da1-test-1 exited with code 137
[+] Running 2/0
 ⠿ Container 1e9da1-test-1  Removed                                                                                                                                       0.0s
 ⠿ Network 1e9da1_default   Removed                                                                                                                                       0.0s
errors detected in your local DAGs are listed above
Error: your local DAGs did not parse. Fix the listed errors or use `astro deploy [deployment-id] -f` to force deploy
```
4. Tried astro deploy <dep-id> -f , it was stuck for long time after this -> Deployed Image Tag:  deploy-2022-10-12T12-39
5. Then got this error msg
```
 Error: write error: ===== RESPONSE ERROR (ErrorCode=AuthenticationFailed) =====
Description=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:0c68dac0-f01e-009b-0839-de1e6a000000
Time:2022-10-12T12:50:42.4004915Z, Details:
   AuthenticationErrorDetail: Signature not valid in the specified time frame: Start [Wed, 12 Oct 2022 12:40:41 GMT] - Expiry [Wed, 12 Oct 2022 12:50:41 GMT] - Current [Wed, 12 Oct 2022 12:50:42 GMT]
```

**What CLI Version did you experience this bug?**

Astro CLI Version: SNAPSHOT-1df11733
Astro CLI Version: 1.5.0

**Comment by dsgupta02** [comment]
Not getting Response Error msg now.

But still unable to deploy large number of dags in a dag file.
Please find the observation here -> https://astronomer.slack.com/archives/C035LAFSSDD/p1665765155863019?thread_ts=1665595267.400269&cid=C035LAFSSDD

**Comment by kushalmalani** [comment]
Confirmed offline with @dsgupta02 . This issue is good to close
