### ISSUE TITLE
Dag deploy feature turning off when deploy custom image.

### ISSUE THREAD

**Issue by dsgupta02** [astronomer/astro-cli#822]
**Describe the bug**

When tried deploying custom image  `./astro deploy cl9cld5td1887773r0h9fhzxzbk -i deeksha`  after enabling the dag deploy using `./astro deployment update cl9cld5td1887773r0h9fhzxzbk --dag-deploy enable`  we can see Dag downloader is Off.

Didn't get any warning that _deploying custom image will turn the dag deploy feature off_ something like that if this is expected.

No dag downloader sidecar
<img width="359" alt="Screenshot 2022-10-18 at 10 34 10 PM" src="https://user-images.githubusercontent.com/100349882/196497716-6c3c958c-631f-4f9a-8347-6f558f6e3e48.png">

No init container
<img width="1227" alt="Screenshot 2022-10-18 at 10 35 19 PM" src="https://user-images.githubusercontent.com/100349882/196497892-0fce7780-f7f2-4f38-8f7b-9b727e3e4e14.png">

**Comment by kushalmalani** [comment]
We plan to throw an error asking user to contact astronomer support to disable dag deploy
