### ISSUE TITLE
SQL CLI Beta Integration

### ISSUE THREAD

**Issue by sunkickr** [astronomer/astro-cli#825]
- [X] I have checked that a similar [feature request](https://github.com/astronomer/astro-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**✍️ Is your feature request related to a problem? Please describe.**

SQL CLI beta integration with the Astro CLI. The SQL CLI will be nested under the astro cli as `astro flow`

**🧩 Describe the solution you'd like**

**🤔 Describe alternatives you've considered**

**💡 Additional context**

**Comment by kushalmalani** [comment]
@sunkickr @pankajkoti Going to close this out
