### ISSUE TITLE
Astro runtime not compatible with Docker Desktop v4.13.0

### ISSUE THREAD

**Issue by kwheeler27** [astronomer/astro-cli#835]
**Describe the bug**

The Astro runtime gets caught in a recurring start/restart loop when trying to spinning up Airflow containers via Docker Desktop v4.13.0. The containers log the following error message to the Docker UI/console:

```
[FATAL tini (1)] PR_SET_CHILD_SUBREAPER is unavailable on this platform. Are you using Linux >= 3.4?
```

**What CLI Version did you experience this bug?**

Both 1.6.0 and 1.5.0

**What Operating System is the above CLI installed on?**

This error occurred for both MacOS Monterey (12.6) and Ventura (13.0), using an Apple Silicon (m1) chip

**🪜 Steps To Reproduce**

1. Install Docker Desktop v4.13.0 running on a MacOS m1 chip
2. Specify Astro runtime versions of 6.0.1 or 6.0.2 in the Dockerfile of the Astro project
3. Run `astro dev start`
4. Watch it hang

**📸 Screenshots**

<img width="1228" alt="Screen Shot 2022-10-23 at 10 56 03 AM" src="https://user-images.githubusercontent.com/3825300/197644963-52a143df-d482-4ec5-87e4-ea57f8c83ad7.png">

**Comment by kushalmalani** [comment]
@pohek321 @kwheeler27 Seems like this issue got resolved with 4.13.1. I can confirm by upgrading docker to 4.13.1 and was able to run astro dev start locally.

From the release notes - https://docs.docker.com/desktop/release-notes/

`Reverted Qemu to 6.2.0 to fix errors like PR_SET_CHILD_SUBREAPER is unavailable when running emulated amd64 code.`

**Comment by kushalmalani** [comment]
@kwheeler27 Are you still seeing the issue after upgrading to 4.13.1?

**Comment by kushalmalani** [comment]
Going to close this one out. Feel free to re-open if the issue persists.
