### ISSUE TITLE
Enable shouldDisplayLoginLink for organization switch.

### ISSUE THREAD

**Issue by guohui-gao** [astronomer/astro-cli#838]
- [ ] I have checked that a similar [feature request](https://github.com/astronomer/astro-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**✍️ Is your feature request related to a problem? Please describe.**
I am now working on move e2e test to a new org and it need to run organization switch in the e2e cli tests. but the current organization switch always set shouldDisplayLoginLink as false to login. which blocks me from switch org in the cypress tests. 

**🧩 Describe the solution you'd like**
either enable shouldDisplayLoginLink (--login-link) for organization switch.
Or, if we login and the auth is still valid. don't prompt for login.

**🤔 Describe alternatives you've considered**

**💡 Additional context**

**Comment by kushalmalani** [comment]
@guohui-gao Is this good to close?
