### ISSUE TITLE
Could not use astro cli if home directory is read only

### ISSUE THREAD

**Issue by sreenusuuda** [astronomer/astro-cli#848]
**Describe the bug**

I am using Lambda function to push dags from s3 bucket to astro cloud. As home directory is read only in Lambda function I could not login either using -t <token> or could not deploy dags using deployment API key as both approaches will create/update .astro directory in the home directory. 

Shall we have some way to configure .astro path?

```
Here is the message I got in the output:
Error creating default config in home dir: error creating config directory: mkdir /home/sbx_user1051: read-only file systemError: error saving config: open /home/sbx_user1051/.astro/config.yaml: no such file or directory
Error: no context set, have you authenticated to Astro or Astronomer Software? Run astro login and try again
```

**What CLI Version did you experience this bug?**
1.7.0 ( Applicable to all versions)

**What Operating System is the above CLI installed on?**

**🪜 Steps To Reproduce**

1. Upload astro binary zip file to s3 bucket.
2. Execute below lambda function.(Make sure you update zip file name in the lambda function)

Lambda Function: 

**📸 Screenshots**

<img width="1011" alt="Screenshot 2022-11-01 at 12 33 54 PM" src="https://user-images.githubusercontent.com/99465779/199177715-c86950c1-101c-4c1f-8139-656c56511726.png">

**Comment by ernest-kr** [comment]
@sreenusuuda as suggested by David
have this 

put dags and config file into /tmp
cd into tmp
run astro deploy --dags
