### ISSUE TITLE
Error in astro dev start if directory name contains space in it.

### ISSUE THREAD

**Issue by sreenusuuda** [astronomer/astro-cli#859]
**Describe the bug**

Getting below error when we run astro binary directly using './astro dev start' from a folder where directory name has blank space. 

**Error Message:** command 'docker build -t astro-1-7-0-darwin-arm-64-(2)_32de62/airflow:latest failed: failed to execute cmd: exit status 125

**What CLI Version did you experience this bug?**

1.7.0 (I guess older versions also have same issue)

**What Operating System is the above CLI installed on?**

Darwin

**🪜 Steps To Reproduce**

1. Create a directory with name contains space like 'astro binary'
2. Download binary from git hub releases and put into above directory.
3. run ./astro dev init from that directory
4. run ./astro dev start from that directory

**Comment by kushalmalani** [comment]
@sreenusuuda I am not able to replicate this. I dont think the issue is the folder naming...i am able to dev start properly with a folder with a name that has a space. I think the issue is with the binary being added to the airflow project, which is not a common practice.

**Comment by sreenusuuda** [comment]
@kushalmalani , Yes its because of astro binary available in a directory name having space. Closing this as it is not real case scenario.
