### ISSUE TITLE
`astro dev start` not picking up docker compose override

### ISSUE THREAD

**Issue by neel-astro** [astronomer/astro-cli#867]
**Describe the bug**
With recent changes in `1.7.0`, it seems like `astro dev start` or `astro dev restart` is not picking up the docker-compose override file content while bringing up the local airflow setup

Reference: https://astronomer.slack.com/archives/CL44PA4DB/p1668081751784339

**What CLI Version did you experience this bug?**
`1.7.0`

**Comment by kushalmalani** [comment]
@neel-astro Going to close this one out, since 1.8 is out
