### ISSUE TITLE
Allow exposing ports to the world in Astro CLI via flag

### ISSUE THREAD

**Issue by rbankston** [astronomer/astro-cli#878]
**Describe the bug**

Following the closure of #685 if a team of users used astro dev start as a shared development environment the limiting of ports to localhost only would break this use case. 

**What CLI Version did you experience this bug?**

1.7.0+

Possible solution: By adding a flag that removes the localhost restriction in the generated docker compose file

**Comment by sunkickr** [comment]
could you use the docker compose override file to add ports to the webserver?

**Comment by pro100filipp** [comment]
Setting up ports in compose override file results in this message
```Error: error building, (re)creating or starting project containers: Error response from daemon: driver failed programming external connectivity on endpoint astro-airflow_9ad47a-webserver-1 (e46de3f4862b26f2a0b9645bb5a0e11f1c59ebc16a89b62e8d5f2c753743358e): Error starting userland proxy: listen tcp4 0.0.0.0:8080: bind: address already in use
```
As I understood this is because there's a conflict with default localhost port binding provided by astro compose file. So the workaround for now is to provide a different port (e.g. 8081).

I think it'd be a little bit cleaner if there was a flag or something but this solution still solves the problem.

**Comment by rbankston** [comment]
Was only able to get this to work by creating a docker-override.yml of:

```
version: "3.4"
services:
  webserver:
    ports:
     - 0.0.0.0:8081:8081
```

and then adding the following to the Dockerfile:

```
ENV AIRFLOW__WEBSERVER__BASE_URL="http://<vm ip>:8081"
ENV AIRFLOW__WEBSERVER__WEB_SERVER_PORT=8081
ENV AIRFLOW__WEBSERVER__ENDPOINT_URL="http://<vm ip>:8081"
```

**Comment by neel-astro** [comment]
from astro cli version 1.12.0 onwards, one can set `airflow.expose_port` in CLI config to true to expose the webserver & postgres port over `0.0.0.0` which should help resolve your issue.

command to set the config: `astro config set -g airflow.expose_port true`
