### ISSUE TITLE
Test S3 lambda functions for DAG based deployment

### ISSUE THREAD

**Issue by wei-astronomer** [astronomer/astro-cli#888]
When MWAA customers manually uploads DAGs to S3, we build a lambda function listening to the S3 bucket. When the S3 bucket gets update, it trigger a DAG deploy. This is to test the newly implemented mechanism.

**Comment by sreenusuuda** [comment]
Tested dag deploy using lambda function. It is working fine. 

Here is the github repo for lambda function
https://github.com/astronomer/s3_to_astro
