### ISSUE TITLE
Hard delete from CLI is not working as expected with software

### ISSUE THREAD

**Issue by Priyanka13Astro** [astronomer/astro-cli#913]
**Describe the bug**
Install the software with `manualReleaseNames:true`
Create the deployment in software & hard delete it using below CLI command 
`astro deployment delete <deployment-uuid> --hard`

Command executes successfully but when trying to create the deployment with same releaseName as of depleted, it is throwing Unique constraint error.

Please paste terminal or playground output in a code block here
```
(base) priyanka@PriyankaGs-MacBook-Pro 0.30.0 % astro deployment delete claw3lhe5931614lcg2u96gtg --hard --verbosity debug

Warning: This action permanently deletes all data associated with this Deployment, including the database. You will not be able to recover it. Proceed with hard delete? (y/n) y
DEBU[0004] Request Data: {"query":"\n\tmutation DeleteDeployment(\n\t\t$deploymentId: Uuid!\n\t\t$deploymentHardDelete: Boolean\n\t){\n\t\tdeleteDeployment(\n\t\t\tdeploymentUuid: $deploymentId\n\t\t\tdeploymentHardDelete: $deploymentHardDelete\n\t\t){\n\t\t\tid\n\t\t\ttype\n\t\t\tlabel\n\t\t\tdescription\n\t\t\treleaseName\n\t\t\tversion\n\t\t\tworkspace {\n\t\t\t\tid\n\t\t\t}\n\t\t\tcreatedAt\n\t\t\tupdatedAt\n\t\t}\n\t}","variables":{"deploymentId":"claw3lhe5931614lcg2u96gtg","delpoymentHardDelete":true}} 
DEBU[0004] Response Data: {"data":{"deleteDeployment":{"id":"claw3lhe5931614lcg2u96gtg","type":"airflow","label":"test-preupgrade-ac11015-celery","description":"","releaseName":"test-preupgrade-ac11015-celery","version":"1.7.3-rc2","workspace":{"id":"clavd9gdk009614kenrybrwkp"},"createdAt":"2022-11-25T06:03:48.173Z","updatedAt":"2022-11-29T12:48:44.017Z"}}}
 

 Successfully deleted deployment
```
**What CLI Version did you experience this bug?**
1.8.0

<img width="1714" alt="Screenshot 2022-11-29 at 5 43 56 PM" src="https://user-images.githubusercontent.com/104027503/204536158-cf97734d-341f-4330-9d5e-94b13acf2d6f.png">

**Comment by neel-astro** [comment]
<img width="1276" alt="Screenshot 2022-11-30 at 11 33 16 AM" src="https://user-images.githubusercontent.com/92356010/204970801-c5192422-d09e-410e-a3d2-adbf81e0f886.png">
