### ISSUE TITLE
add utils directory to astro dev init

### ISSUE THREAD

**Issue by sunkickr** [astronomer/astro-cli#925]
- [X] I have checked that a similar [feature request](https://github.com/astronomer/astro-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**✍️ Is your feature request related to a problem? Please describe.**

To get the most use out the dag deploy feature users should store their helper functions in their dags folder. Today `astro dev init` 
encourages users to store their helper functions in an include folder outside their dags folder.

**🧩 Describe the solution you'd like**

Update directory produced by dev init

**🤔 Describe alternatives you've considered**

**Is your feature request specific to a particular Astronomer Platform?**

- [X] Astro
- [ ] Software
- [ ] None/Unknown

**💡 Additional context**

https://www.notion.so/astronomerio/astro-dev-init-Update-for-DAG-Deploy-9008ae5fa1fd4856b3f7fb2293e0f2fc

**Comment by diman82** [comment]
Any progress with this feature? I would like to request to include the 'include' directory (from project root) as well
