### ISSUE TITLE
Send `utils` folder to dag downloader along with `dags` folder

### ISSUE THREAD

**Issue by sunkickr** [astronomer/astro-cli#946]
- [X] I have checked that a similar [feature request](https://github.com/astronomer/astro-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**✍️ Is your feature request related to a problem? Please describe.**

Users will create common python utils that are used by DAGs. These files should be sent up to the dag downloader along with dags folder

**🧩 Describe the solution you'd like**

Both the `dags` and `utils` folders are tar balled and sent to the dag downloader. The Dag downloader should be able to handle and create volumes for both folders

**🤔 Describe alternatives you've considered**

**Is your feature request specific to a particular Astronomer Platform?**

- [X] Astro
- [ ] Software
- [ ] None/Unknown

**💡 Additional context**

https://astronomer.productboard.com/feature-board/2193567-step-1-feature-backlog/features/16912542/detail

**Comment by wei-astronomer** [comment]
Need to cover new test cases and it is challenging to make it in CLI 1.9. Will check the release plan.

**Comment by sunkickr** [comment]
We have decided not to do this
