### ISSUE TITLE
Clean up dev start timeout copy

### ISSUE THREAD

**Issue by sunkickr** [astronomer/astro-cli#950]
**Describe the bug**

Clean up the following copy to better describe what is going on:

```
Project is not running. Run 'astro dev logs --webserver | --scheduler' for details.
Error: webserver failed to start: timed out after 1m0s
```

The webserver did not fail to start it just failed to become healthy within the timeout time(default 1m). better describe what happened and what is needed to fix the problem.

The user should try looking at the webserver logs to see if something went wrong. If the webserver is still starting up and nothing is wrong they should increase the timeout time with --wait

**What CLI Version did you experience this bug?**

1.8.1

**This CLI bug is related to which Astronomer Platform?**

- [X] Astro
- [X] Software
- [ ] None/Unknown

**What Operating System is the above CLI installed on?**

**🪜 Steps To Reproduce**

**📸 Screenshots**

**Comment by sunkickr** [comment]
slack conversation: https://astronomer.slack.com/archives/CL44PA4DB/p1670986041024029

**Comment by diman82** [comment]
I'm facing the same issue even with the latest CLI (1.10)
@sunkickr How this issue can be resolved?
