### ISSUE TITLE
astro deployment list --all does not work

### ISSUE THREAD

**Issue by srayarao** [astronomer/astro-cli#952]
The following command in astro cli is not working:

`astro deployment list --all `

Returns the  following when executed

`Error: API error (400): {"errors":[{"message":"Variable \"$workspaceId\" of required type \"Uuid!\" was not provided.","extensions":{"code":"BAD_USER_INPUT"}}]}`

**Comment by sunkickr** [comment]
This has been fixed as of v1.14.1
