### ISSUE TITLE
make it so users don't need to enter admin:admin into localhost

### ISSUE THREAD

**Issue by sunkickr** [astronomer/astro-cli#957]
- [X] I have checked that a similar [feature request](https://github.com/astronomer/astro-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**✍️ Is your feature request related to a problem? Please describe.**

Users need to enter admin admin every time they start airflow locally

**🧩 Describe the solution you'd like**

Make it so these credentials are automatically entered

**🤔 Describe alternatives you've considered**

**Is your feature request specific to a particular Astronomer Platform?**

- [X] Astro
- [X] Software
- [ ] None/Unknown

**💡 Additional context**

**Comment by kaxil** [comment]
closed by https://github.com/astronomer/astro-cli/pull/955
