### ISSUE TITLE
[triage] min worker count error masked by boilerplate login error

### ISSUE THREAD

**Issue by jcom000** [astronomer/astro-cli#967]
@jcom000 commented on [Mon Dec 19 2022](https://github.com/astronomer/astro/issues/7367)

### Error [Job](https://app.circleci.com/pipelines/github/astronomer/astro/39917/workflows/6987d5a0-8d7c-4996-8b7d-dd438073ba6b/jobs/1152488?invite=true#step-109-72)

```
Error: Cannot connect to Astronomer. Try to log in with astro login or check your internet connection and user permissions.
```

### Description
The error should have read
```
Error: Unable to update min worker count for the m5.xlarge node pool on your cluster, which is over-provisioned by 4 worker(s)
```
https://astronomer.splunkcloud.com/en-US/app/airflow_astro/search?q=search%20index%3Dstage%2A%20%20correlationId%3D%22ac9d5bd5-445c-4efc-a27c-676550a7634d%22&earliest=-4h%40m&latest=now&display.page.search.mode=smart&dispatch.sample_ratio=1&workload_pool=standard_perf&sid=1671477090.815265

**Comment by jemishp** [comment]
I agree as it is misleading to point to a connection issue when we know exactly what went wrong. Will fix the error message.
