### ISSUE TITLE
Update CLI UX to Handle New Auth Mechanics

### ISSUE THREAD

**Issue by gregbrunk** [astronomer/astro-cli#98]
_placeholder ticket to support any changes in Astro-CLI that result from:_
- https://app.zenhub.com/workspace/o/astronomerio/houston-api/issues/36
- https://app.zenhub.com/workspace/o/astronomerio/houston-api/issues/37
- https://app.zenhub.com/workspace/o/astronomerio/houston-api/issues/38

**Comment by schnie** [comment]
@andscoop is the CLI ready to roll for the new user/pass auth flows? Are we still blocked by anything?

**Comment by andscoop** [comment]
@schnie Basics are in place, but from a previous discussion with @cwurtz there is a slight change in flow that I need to discuss with him. I can knock this out quickly after that.
