### ISSUE TITLE
No success message when create deployment using yaml file

### ISSUE THREAD

**Issue by dsgupta02** [astronomer/astro-cli#984]
**Describe the bug**

We don't get confirmation/success message once we create deployment using yaml file. We just get the yaml content printed in cmd. Can we get the success msg as we get for astro deploy?

**📸 Screenshots**

<img width="1233" alt="Screenshot 2022-12-22 at 9 00 50 PM" src="https://user-images.githubusercontent.com/100349882/209168048-9fc73998-7aef-4844-9c84-0d3685aa3e5d.png">

**Comment by sunkickr** [comment]
we print just the yaml so users can easily transfer this content to a file. `astro deployment create --from-file > file.yaml`
